
# This file is automatically generated, you probably don't want to edit this

.jmvrefs <- list(
    `snowCluster`=list(
        `type`="software", 
        `author`="Seol, H.", 
        `year`=2020, 
        `title`="snowCluster: Cluster Analysis for jamovi", 
        `publisher`="[jamovi module]. Retrieved from https://github.com/hyunsooseol/snowCluster/", 
        `url`="https://github.com/hyunsooseol/snowCluster"))
