
# This file is automatically generated, you probably don't want to edit this

arimaOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "arimaOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            dep = NULL,
            time = NULL,
            freq = 12,
            pred = 10,
            plot = TRUE,
            box = FALSE,
            plot1 = FALSE,
            plot2 = FALSE,
            plot3 = FALSE,
            coef = TRUE,
            fit = FALSE,
            point = FALSE,
            plot4 = FALSE, ...) {

            super$initialize(
                package="snowCluster",
                name="arima",
                requiresData=TRUE,
                ...)

            private$..dep <- jmvcore::OptionVariable$new(
                "dep",
                dep,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..time <- jmvcore::OptionVariables$new(
                "time",
                time,
                rejectUnusedLevels=TRUE,
                suggested=list(
                    "nominal"),
                default=NULL)
            private$..freq <- jmvcore::OptionInteger$new(
                "freq",
                freq,
                min=1,
                default=12)
            private$..pred <- jmvcore::OptionInteger$new(
                "pred",
                pred,
                min=1,
                default=10)
            private$..plot <- jmvcore::OptionBool$new(
                "plot",
                plot,
                default=TRUE)
            private$..box <- jmvcore::OptionBool$new(
                "box",
                box,
                default=FALSE)
            private$..plot1 <- jmvcore::OptionBool$new(
                "plot1",
                plot1,
                default=FALSE)
            private$..plot2 <- jmvcore::OptionBool$new(
                "plot2",
                plot2,
                default=FALSE)
            private$..plot3 <- jmvcore::OptionBool$new(
                "plot3",
                plot3,
                default=FALSE)
            private$..coef <- jmvcore::OptionBool$new(
                "coef",
                coef,
                default=TRUE)
            private$..fit <- jmvcore::OptionBool$new(
                "fit",
                fit,
                default=FALSE)
            private$..point <- jmvcore::OptionBool$new(
                "point",
                point,
                default=FALSE)
            private$..plot4 <- jmvcore::OptionBool$new(
                "plot4",
                plot4,
                default=FALSE)

            self$.addOption(private$..dep)
            self$.addOption(private$..time)
            self$.addOption(private$..freq)
            self$.addOption(private$..pred)
            self$.addOption(private$..plot)
            self$.addOption(private$..box)
            self$.addOption(private$..plot1)
            self$.addOption(private$..plot2)
            self$.addOption(private$..plot3)
            self$.addOption(private$..coef)
            self$.addOption(private$..fit)
            self$.addOption(private$..point)
            self$.addOption(private$..plot4)
        }),
    active = list(
        dep = function() private$..dep$value,
        time = function() private$..time$value,
        freq = function() private$..freq$value,
        pred = function() private$..pred$value,
        plot = function() private$..plot$value,
        box = function() private$..box$value,
        plot1 = function() private$..plot1$value,
        plot2 = function() private$..plot2$value,
        plot3 = function() private$..plot3$value,
        coef = function() private$..coef$value,
        fit = function() private$..fit$value,
        point = function() private$..point$value,
        plot4 = function() private$..plot4$value),
    private = list(
        ..dep = NA,
        ..time = NA,
        ..freq = NA,
        ..pred = NA,
        ..plot = NA,
        ..box = NA,
        ..plot1 = NA,
        ..plot2 = NA,
        ..plot3 = NA,
        ..coef = NA,
        ..fit = NA,
        ..point = NA,
        ..plot4 = NA)
)

arimaResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "arimaResults",
    inherit = jmvcore::Group,
    active = list(
        instructions = function() private$.items[["instructions"]],
        text = function() private$.items[["text"]],
        coef = function() private$.items[["coef"]],
        fit = function() private$.items[["fit"]],
        point = function() private$.items[["point"]],
        plot = function() private$.items[["plot"]],
        box = function() private$.items[["box"]],
        plot1 = function() private$.items[["plot1"]],
        plot2 = function() private$.items[["plot2"]],
        plot3 = function() private$.items[["plot3"]],
        plot4 = function() private$.items[["plot4"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Univariate time series",
                refs="snowCluster")
            self$add(jmvcore::Html$new(
                options=options,
                name="instructions",
                title="Instructions",
                visible=TRUE))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title=""))
            self$add(jmvcore::Table$new(
                options=options,
                name="coef",
                title="Model coefficients",
                visible="(coef)",
                clearWith=list(
                    "dep"),
                columns=list(
                    list(
                        `name`="name", 
                        `title`="", 
                        `type`="text", 
                        `content`="($key)"),
                    list(
                        `name`="co", 
                        `title`="Estimate", 
                        `type`="number"),
                    list(
                        `name`="se", 
                        `title`="SE", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="fit",
                title="Model fit",
                visible="(fit)",
                clearWith=list(
                    "dep"),
                columns=list(
                    list(
                        `name`="name", 
                        `title`="Fit Measures", 
                        `type`="text", 
                        `content`="($key)"),
                    list(
                        `name`="value", 
                        `title`="Value"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="point",
                title="Prediction intervals",
                visible="(point)",
                refs="forecast",
                clearWith=list(
                    "dep"),
                columns=list(
                    list(
                        `name`="name", 
                        `title`="", 
                        `type`="text", 
                        `content`="($key)"),
                    list(
                        `name`="po", 
                        `title`="Point forecast", 
                        `type`="number"),
                    list(
                        `name`="lower", 
                        `title`="Lower", 
                        `type`="number", 
                        `superTitle`="95% CI"),
                    list(
                        `name`="upper", 
                        `title`="Upper", 
                        `type`="number", 
                        `superTitle`="95% CI"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="Decomposition",
                visible="(plot)",
                width=500,
                height=500,
                renderFun=".plot"))
            self$add(jmvcore::Image$new(
                options=options,
                name="box",
                title="Box plot",
                requiresData=TRUE,
                visible="(box)",
                width=500,
                height=300,
                renderFun=".box"))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot1",
                title="Automatic ARIMA forecasts",
                visible="(plot1)",
                width=500,
                height=500,
                renderFun=".plot1"))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot2",
                title="Residual plot",
                visible="(plot2)",
                width=500,
                height=500,
                renderFun=".plot2"))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot3",
                title="Prediction",
                visible="(plot3)",
                refs="forecast",
                width=500,
                height=500,
                renderFun=".plot3"))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot4",
                title="Exploring dataset",
                visible="(plot4)",
                refs="prophet",
                width=500,
                height=500,
                renderFun=".plot4"))}))

arimaBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "arimaBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "snowCluster",
                name = "arima",
                version = c(1,0,0),
                options = options,
                results = arimaResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Univariate time series
#'
#' 
#' @param data timeseries data format
#' @param dep the dependent variable from \code{data}, variable must be
#'   numeric
#' @param time the fixed factors from \code{data}
#' @param freq .
#' @param pred .
#' @param plot .
#' @param box .
#' @param plot1 .
#' @param plot2 .
#' @param plot3 .
#' @param coef .
#' @param fit .
#' @param point .
#' @param plot4 .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$instructions} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$coef} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$fit} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$point} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$box} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plot1} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plot2} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plot3} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plot4} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$coef$asDF}
#'
#' \code{as.data.frame(results$coef)}
#'
#' @export
arima <- function(
    data,
    dep,
    time = NULL,
    freq = 12,
    pred = 10,
    plot = TRUE,
    box = FALSE,
    plot1 = FALSE,
    plot2 = FALSE,
    plot3 = FALSE,
    coef = TRUE,
    fit = FALSE,
    point = FALSE,
    plot4 = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("arima requires jmvcore to be installed (restart may be required)")

    if ( ! missing(dep)) dep <- jmvcore::resolveQuo(jmvcore::enquo(dep))
    if ( ! missing(time)) time <- jmvcore::resolveQuo(jmvcore::enquo(time))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(dep), dep, NULL),
            `if`( ! missing(time), time, NULL))


    options <- arimaOptions$new(
        dep = dep,
        time = time,
        freq = freq,
        pred = pred,
        plot = plot,
        box = box,
        plot1 = plot1,
        plot2 = plot2,
        plot3 = plot3,
        coef = coef,
        fit = fit,
        point = point,
        plot4 = plot4)

    analysis <- arimaClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

