
# This file is automatically generated, you probably don't want to edit this

caretOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "caretOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            dep = NULL,
            covs = NULL,
            scale = NULL,
            mecon = NULL,
            method = "pls",
            cm1 = "knn",
            number = 10,
            repeats = 5,
            tune = 10,
            per = 0.7,
            over1 = TRUE,
            over = FALSE,
            cla = FALSE,
            cla1 = FALSE,
            tra = TRUE,
            tes = FALSE,
            plot = TRUE,
            plot1 = FALSE,
            plot2 = TRUE,
            plot3 = TRUE, ...) {

            super$initialize(
                package="snowCluster",
                name="caret",
                requiresData=TRUE,
                ...)

            private$..dep <- jmvcore::OptionVariable$new(
                "dep",
                dep,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..covs <- jmvcore::OptionVariables$new(
                "covs",
                covs)
            private$..scale <- jmvcore::OptionList$new(
                "scale",
                scale,
                options=list(
                    "stand",
                    "normal",
                    "pca"))
            private$..mecon <- jmvcore::OptionList$new(
                "mecon",
                mecon,
                options=list(
                    "cv",
                    "repeatedcv",
                    "boot"))
            private$..method <- jmvcore::OptionList$new(
                "method",
                method,
                options=list(
                    "pls",
                    "ctree",
                    "knn",
                    "rpart",
                    "ranger",
                    "nnet",
                    "neuralnet",
                    "avNNet",
                    "xgbTree",
                    "gbm",
                    "fda",
                    "mda",
                    "bag"),
                default="pls")
            private$..cm1 <- jmvcore::OptionList$new(
                "cm1",
                cm1,
                options=list(
                    "pls",
                    "ctree",
                    "knn",
                    "rpart",
                    "ranger",
                    "nnet",
                    "neuralnet",
                    "avNNet",
                    "xgbTree",
                    "gbm",
                    "fda",
                    "mda",
                    "bag"),
                default="knn")
            private$..number <- jmvcore::OptionNumber$new(
                "number",
                number,
                min=10,
                default=10)
            private$..repeats <- jmvcore::OptionNumber$new(
                "repeats",
                repeats,
                min=5,
                default=5)
            private$..tune <- jmvcore::OptionNumber$new(
                "tune",
                tune,
                min=3,
                default=10)
            private$..per <- jmvcore::OptionNumber$new(
                "per",
                per,
                min=0.1,
                max=1,
                default=0.7)
            private$..over1 <- jmvcore::OptionBool$new(
                "over1",
                over1,
                default=TRUE)
            private$..over <- jmvcore::OptionBool$new(
                "over",
                over,
                default=FALSE)
            private$..cla <- jmvcore::OptionBool$new(
                "cla",
                cla,
                default=FALSE)
            private$..cla1 <- jmvcore::OptionBool$new(
                "cla1",
                cla1,
                default=FALSE)
            private$..tra <- jmvcore::OptionBool$new(
                "tra",
                tra,
                default=TRUE)
            private$..tes <- jmvcore::OptionBool$new(
                "tes",
                tes,
                default=FALSE)
            private$..plot <- jmvcore::OptionBool$new(
                "plot",
                plot,
                default=TRUE)
            private$..plot1 <- jmvcore::OptionBool$new(
                "plot1",
                plot1,
                default=FALSE)
            private$..plot2 <- jmvcore::OptionBool$new(
                "plot2",
                plot2,
                default=TRUE)
            private$..plot3 <- jmvcore::OptionBool$new(
                "plot3",
                plot3,
                default=TRUE)

            self$.addOption(private$..dep)
            self$.addOption(private$..covs)
            self$.addOption(private$..scale)
            self$.addOption(private$..mecon)
            self$.addOption(private$..method)
            self$.addOption(private$..cm1)
            self$.addOption(private$..number)
            self$.addOption(private$..repeats)
            self$.addOption(private$..tune)
            self$.addOption(private$..per)
            self$.addOption(private$..over1)
            self$.addOption(private$..over)
            self$.addOption(private$..cla)
            self$.addOption(private$..cla1)
            self$.addOption(private$..tra)
            self$.addOption(private$..tes)
            self$.addOption(private$..plot)
            self$.addOption(private$..plot1)
            self$.addOption(private$..plot2)
            self$.addOption(private$..plot3)
        }),
    active = list(
        dep = function() private$..dep$value,
        covs = function() private$..covs$value,
        scale = function() private$..scale$value,
        mecon = function() private$..mecon$value,
        method = function() private$..method$value,
        cm1 = function() private$..cm1$value,
        number = function() private$..number$value,
        repeats = function() private$..repeats$value,
        tune = function() private$..tune$value,
        per = function() private$..per$value,
        over1 = function() private$..over1$value,
        over = function() private$..over$value,
        cla = function() private$..cla$value,
        cla1 = function() private$..cla1$value,
        tra = function() private$..tra$value,
        tes = function() private$..tes$value,
        plot = function() private$..plot$value,
        plot1 = function() private$..plot1$value,
        plot2 = function() private$..plot2$value,
        plot3 = function() private$..plot3$value),
    private = list(
        ..dep = NA,
        ..covs = NA,
        ..scale = NA,
        ..mecon = NA,
        ..method = NA,
        ..cm1 = NA,
        ..number = NA,
        ..repeats = NA,
        ..tune = NA,
        ..per = NA,
        ..over1 = NA,
        ..over = NA,
        ..cla = NA,
        ..cla1 = NA,
        ..tra = NA,
        ..tes = NA,
        ..plot = NA,
        ..plot1 = NA,
        ..plot2 = NA,
        ..plot3 = NA)
)

caretResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "caretResults",
    inherit = jmvcore::Group,
    active = list(
        instructions = function() private$.items[["instructions"]],
        text = function() private$.items[["text"]],
        over1 = function() private$.items[["over1"]],
        over = function() private$.items[["over"]],
        tra = function() private$.items[["tra"]],
        tes = function() private$.items[["tes"]],
        cla1 = function() private$.items[["cla1"]],
        cla = function() private$.items[["cla"]],
        plot2 = function() private$.items[["plot2"]],
        plot = function() private$.items[["plot"]],
        plot1 = function() private$.items[["plot1"]],
        plot3 = function() private$.items[["plot3"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Machine Learning",
                refs="snowCluster")
            self$add(jmvcore::Html$new(
                options=options,
                name="instructions",
                title="Instructions",
                visible=TRUE))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="Model information"))
            self$add(jmvcore::Table$new(
                options=options,
                name="over1",
                title="Overall statistics with training set",
                rows=1,
                visible="(over1)",
                clearWith=list(
                    "covs",
                    "dep",
                    "scale",
                    "per",
                    "mecon",
                    "number",
                    "repeats",
                    "method",
                    "tune"),
                refs="caret",
                columns=list(
                    list(
                        `name`="accu", 
                        `title`="Accuracy", 
                        `type`="number"),
                    list(
                        `name`="lower", 
                        `title`="Lower", 
                        `type`="number", 
                        `superTitle`="Accuracy 95% CI"),
                    list(
                        `name`="upper", 
                        `title`="Upper", 
                        `type`="number", 
                        `superTitle`="Accuracy 95% CI"),
                    list(
                        `name`="kappa", 
                        `title`="Kappa", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="over",
                title="Overall statistics with test set",
                rows=1,
                visible="(over)",
                clearWith=list(
                    "covs",
                    "dep",
                    "scale",
                    "per",
                    "mecon",
                    "number",
                    "repeats",
                    "method",
                    "tune"),
                refs="caret",
                columns=list(
                    list(
                        `name`="accu", 
                        `title`="Accuracy", 
                        `type`="number"),
                    list(
                        `name`="lower", 
                        `title`="Lower", 
                        `type`="number", 
                        `superTitle`="Accuracy 95% CI"),
                    list(
                        `name`="upper", 
                        `title`="Upper", 
                        `type`="number", 
                        `superTitle`="Accuracy 95% CI"),
                    list(
                        `name`="kappa", 
                        `title`="Kappa", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="tra",
                title="Confusion matrix with training set",
                visible="(tra)",
                clearWith=list(
                    "covs",
                    "dep",
                    "scale",
                    "per",
                    "mecon",
                    "number",
                    "repeats",
                    "method",
                    "tune"),
                refs="caret",
                columns=list(
                    list(
                        `name`="name", 
                        `title`="", 
                        `type`="text", 
                        `content`="($key)"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="tes",
                title="Confusion matrix with test set",
                visible="(tes)",
                clearWith=list(
                    "covs",
                    "dep",
                    "scale",
                    "per",
                    "mecon",
                    "number",
                    "repeats",
                    "method",
                    "tune"),
                refs="caret",
                columns=list(
                    list(
                        `name`="name", 
                        `title`="", 
                        `type`="text", 
                        `content`="($key)"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="cla1",
                title="Statistics by class with training set",
                visible="(cla1)",
                refs="caret",
                clearWith=list(
                    "covs",
                    "dep",
                    "scale",
                    "per",
                    "mecon",
                    "number",
                    "repeats",
                    "method",
                    "tune"),
                columns=list(
                    list(
                        `name`="name", 
                        `title`="", 
                        `type`="text", 
                        `content`="($key)"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="cla",
                title="Statistics by class with test set",
                visible="(cla)",
                refs="caret",
                clearWith=list(
                    "covs",
                    "dep",
                    "scale",
                    "per",
                    "mecon",
                    "number",
                    "repeats",
                    "method",
                    "tune"),
                columns=list(
                    list(
                        `name`="name", 
                        `title`="", 
                        `type`="text", 
                        `content`="($key)"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot2",
                title="Model selection plot",
                visible="(plot2)",
                width=500,
                height=300,
                renderFun=".plot2",
                refs="caret",
                clearWith=list(
                    "covs",
                    "dep",
                    "scale",
                    "per",
                    "mecon",
                    "number",
                    "repeats",
                    "method",
                    "tune")))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="ROC plot with training set",
                visible="(plot)",
                width=500,
                height=500,
                renderFun=".plot",
                refs="caret",
                clearWith=list(
                    "covs",
                    "dep",
                    "scale",
                    "per",
                    "mecon",
                    "number",
                    "repeats",
                    "method",
                    "tune",
                    "cm1")))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot1",
                title="Variable importance plot",
                visible="(plot1)",
                width=600,
                height=600,
                renderFun=".plot1",
                refs="caret",
                clearWith=list(
                    "covs",
                    "dep",
                    "scale",
                    "per",
                    "mecon",
                    "number",
                    "repeats",
                    "method",
                    "tune")))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot3",
                title="ROC plot with test set",
                visible="(plot3)",
                width=500,
                height=500,
                renderFun=".plot3",
                refs="caret",
                clearWith=list(
                    "covs",
                    "dep",
                    "scale",
                    "per",
                    "mecon",
                    "number",
                    "repeats",
                    "method",
                    "tune")))}))

caretBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "caretBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "snowCluster",
                name = "caret",
                version = c(1,0,0),
                options = options,
                results = caretResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Machine Learning
#'
#' 
#' @param data .
#' @param dep .
#' @param covs .
#' @param scale .
#' @param mecon .
#' @param method .
#' @param cm1 .
#' @param number .
#' @param repeats .
#' @param tune .
#' @param per .
#' @param over1 .
#' @param over .
#' @param cla .
#' @param cla1 .
#' @param tra .
#' @param tes .
#' @param plot .
#' @param plot1 .
#' @param plot2 .
#' @param plot3 .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$instructions} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$over1} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$over} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$tra} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$tes} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$cla1} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$cla} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$plot2} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plot1} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plot3} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$over1$asDF}
#'
#' \code{as.data.frame(results$over1)}
#'
#' @export
caret <- function(
    data,
    dep,
    covs,
    scale,
    mecon,
    method = "pls",
    cm1 = "knn",
    number = 10,
    repeats = 5,
    tune = 10,
    per = 0.7,
    over1 = TRUE,
    over = FALSE,
    cla = FALSE,
    cla1 = FALSE,
    tra = TRUE,
    tes = FALSE,
    plot = TRUE,
    plot1 = FALSE,
    plot2 = TRUE,
    plot3 = TRUE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("caret requires jmvcore to be installed (restart may be required)")

    if ( ! missing(dep)) dep <- jmvcore::resolveQuo(jmvcore::enquo(dep))
    if ( ! missing(covs)) covs <- jmvcore::resolveQuo(jmvcore::enquo(covs))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(dep), dep, NULL),
            `if`( ! missing(covs), covs, NULL))

    for (v in dep) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- caretOptions$new(
        dep = dep,
        covs = covs,
        scale = scale,
        mecon = mecon,
        method = method,
        cm1 = cm1,
        number = number,
        repeats = repeats,
        tune = tune,
        per = per,
        over1 = over1,
        over = over,
        cla = cla,
        cla1 = cla1,
        tra = tra,
        tes = tes,
        plot = plot,
        plot1 = plot1,
        plot2 = plot2,
        plot3 = plot3)

    analysis <- caretClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

