
# This file is automatically generated, you probably don't want to edit this

correspondenceOptions <- if (requireNamespace('jmvcore')) R6::R6Class(
    "correspondenceOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            labels = NULL,
            vars = NULL,
            chi = TRUE,
            eigen = FALSE,
            plot1 = TRUE,
            plot2 = FALSE,
            plot3 = FALSE, ...) {

            super$initialize(
                package='snowCluster',
                name='correspondence',
                requiresData=TRUE,
                ...)

            private$..labels <- jmvcore::OptionVariable$new(
                "labels",
                labels,
                suggested=list(
                    "id"),
                permitted=list(
                    "id",
                    "factor"))
            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..chi <- jmvcore::OptionBool$new(
                "chi",
                chi,
                default=TRUE)
            private$..eigen <- jmvcore::OptionBool$new(
                "eigen",
                eigen,
                default=FALSE)
            private$..plot1 <- jmvcore::OptionBool$new(
                "plot1",
                plot1,
                default=TRUE)
            private$..plot2 <- jmvcore::OptionBool$new(
                "plot2",
                plot2,
                default=FALSE)
            private$..plot3 <- jmvcore::OptionBool$new(
                "plot3",
                plot3,
                default=FALSE)

            self$.addOption(private$..labels)
            self$.addOption(private$..vars)
            self$.addOption(private$..chi)
            self$.addOption(private$..eigen)
            self$.addOption(private$..plot1)
            self$.addOption(private$..plot2)
            self$.addOption(private$..plot3)
        }),
    active = list(
        labels = function() private$..labels$value,
        vars = function() private$..vars$value,
        chi = function() private$..chi$value,
        eigen = function() private$..eigen$value,
        plot1 = function() private$..plot1$value,
        plot2 = function() private$..plot2$value,
        plot3 = function() private$..plot3$value),
    private = list(
        ..labels = NA,
        ..vars = NA,
        ..chi = NA,
        ..eigen = NA,
        ..plot1 = NA,
        ..plot2 = NA,
        ..plot3 = NA)
)

correspondenceResults <- if (requireNamespace('jmvcore')) R6::R6Class(
    inherit = jmvcore::Group,
    active = list(
        chi = function() private$.items[["chi"]],
        eigen = function() private$.items[["eigen"]],
        plot1 = function() private$.items[["plot1"]],
        plot2 = function() private$.items[["plot2"]],
        plot3 = function() private$.items[["plot3"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Correspondence Analysis",
                refs="snowCluster")
            self$add(jmvcore::Table$new(
                options=options,
                name="chi",
                title="Chi-square test",
                rows=1,
                clearWith=list(
                    "vars"),
                columns=list(
                    list(
                        `name`="name", 
                        `title`="", 
                        `type`="text", 
                        `content`="X-squared"),
                    list(
                        `name`="statistic", 
                        `type`="number"),
                    list(
                        `name`="df", 
                        `type`="number"),
                    list(
                        `name`="p", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="eigen",
                title="Eigenvalues",
                visible="(eigen)",
                clearWith=list(
                    "vars"),
                columns=list(
                    list(
                        `name`="comp", 
                        `title`="Component", 
                        `type`="text"),
                    list(
                        `name`="eigen", 
                        `title`="Eigenvalue", 
                        `type`="number"),
                    list(
                        `name`="varProp", 
                        `title`="% of Variance", 
                        `type`="number"),
                    list(
                        `name`="varCum", 
                        `title`="Cumulative %", 
                        `type`="number"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot1",
                title="Row points",
                requiresData=TRUE,
                refs="factoextra",
                visible="(plot1)",
                width=500,
                height=500,
                renderFun=".plot1"))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot2",
                title="Column points",
                requiresData=TRUE,
                refs="factoextra",
                visible="(plot2)",
                width=500,
                height=500,
                renderFun=".plot2"))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot3",
                title="Biplot",
                requiresData=TRUE,
                refs="factoextra",
                visible="(plot3)",
                width=500,
                height=500,
                renderFun=".plot3"))}))

correspondenceBase <- if (requireNamespace('jmvcore')) R6::R6Class(
    "correspondenceBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = 'snowCluster',
                name = 'correspondence',
                version = c(1,0,0),
                options = options,
                results = correspondenceResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Correspondence Analysis
#'
#' 
#' @param data The data as a data frame.
#' @param labels .
#' @param vars .
#' @param chi .
#' @param eigen .
#' @param plot1 .
#' @param plot2 .
#' @param plot3 .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$chi} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$eigen} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$plot1} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plot2} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plot3} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$chi$asDF}
#'
#' \code{as.data.frame(results$chi)}
#'
#' @export
correspondence <- function(
    data,
    labels,
    vars,
    chi = TRUE,
    eigen = FALSE,
    plot1 = TRUE,
    plot2 = FALSE,
    plot3 = FALSE) {

    if ( ! requireNamespace('jmvcore'))
        stop('correspondence requires jmvcore to be installed (restart may be required)')

    if ( ! missing(labels)) labels <- jmvcore::resolveQuo(jmvcore::enquo(labels))
    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(labels), labels, NULL),
            `if`( ! missing(vars), vars, NULL))

    for (v in vars) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- correspondenceOptions$new(
        labels = labels,
        vars = vars,
        chi = chi,
        eigen = eigen,
        plot1 = plot1,
        plot2 = plot2,
        plot3 = plot3)

    analysis <- correspondenceClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}
