
# This file is automatically generated, you probably don't want to edit this

dbscanOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "dbscanOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars = NULL,
            eps = 0.5,
            minPts = 5,
            standardize = FALSE,
            dist = "euclidean",
            sizeTable = FALSE,
            plot = FALSE,
            profileTable = FALSE,
            prostat = "mean",
            knnPlot = FALSE,
            autoEps = FALSE,
            epsQuantile = 0.95,
            quality = FALSE,
            qoption = "none",
            width = 500,
            height = 500,
            width1 = 500,
            height1 = 500, ...) {

            super$initialize(
                package="snowCluster",
                name="dbscan",
                requiresData=TRUE,
                ...)

            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars,
                suggested=list(
                    "continuous",
                    "ordinal",
                    "nominal"),
                permitted=list(
                    "numeric",
                    "factor"))
            private$..eps <- jmvcore::OptionNumber$new(
                "eps",
                eps,
                default=0.5,
                min=0.01)
            private$..minPts <- jmvcore::OptionInteger$new(
                "minPts",
                minPts,
                default=5,
                min=2)
            private$..standardize <- jmvcore::OptionBool$new(
                "standardize",
                standardize,
                default=FALSE)
            private$..dist <- jmvcore::OptionList$new(
                "dist",
                dist,
                options=list(
                    "euclidean",
                    "manhattan",
                    "maximum",
                    "binary",
                    "gower"),
                default="euclidean")
            private$..cm <- jmvcore::OptionOutput$new(
                "cm")
            private$..sizeTable <- jmvcore::OptionBool$new(
                "sizeTable",
                sizeTable,
                default=FALSE)
            private$..plot <- jmvcore::OptionBool$new(
                "plot",
                plot,
                default=FALSE)
            private$..profileTable <- jmvcore::OptionBool$new(
                "profileTable",
                profileTable,
                default=FALSE)
            private$..prostat <- jmvcore::OptionList$new(
                "prostat",
                prostat,
                default="mean",
                options=list(
                    "mean",
                    "median"))
            private$..knnPlot <- jmvcore::OptionBool$new(
                "knnPlot",
                knnPlot,
                default=FALSE)
            private$..autoEps <- jmvcore::OptionBool$new(
                "autoEps",
                autoEps,
                default=FALSE)
            private$..epsQuantile <- jmvcore::OptionNumber$new(
                "epsQuantile",
                epsQuantile,
                min=0.5,
                max=0.999,
                default=0.95)
            private$..quality <- jmvcore::OptionBool$new(
                "quality",
                quality,
                default=FALSE)
            private$..qoption <- jmvcore::OptionList$new(
                "qoption",
                qoption,
                default="none",
                options=list(
                    "none",
                    "sil",
                    "dbi"))
            private$..width <- jmvcore::OptionInteger$new(
                "width",
                width,
                default=500)
            private$..height <- jmvcore::OptionInteger$new(
                "height",
                height,
                default=500)
            private$..width1 <- jmvcore::OptionInteger$new(
                "width1",
                width1,
                default=500)
            private$..height1 <- jmvcore::OptionInteger$new(
                "height1",
                height1,
                default=500)

            self$.addOption(private$..vars)
            self$.addOption(private$..eps)
            self$.addOption(private$..minPts)
            self$.addOption(private$..standardize)
            self$.addOption(private$..dist)
            self$.addOption(private$..cm)
            self$.addOption(private$..sizeTable)
            self$.addOption(private$..plot)
            self$.addOption(private$..profileTable)
            self$.addOption(private$..prostat)
            self$.addOption(private$..knnPlot)
            self$.addOption(private$..autoEps)
            self$.addOption(private$..epsQuantile)
            self$.addOption(private$..quality)
            self$.addOption(private$..qoption)
            self$.addOption(private$..width)
            self$.addOption(private$..height)
            self$.addOption(private$..width1)
            self$.addOption(private$..height1)
        }),
    active = list(
        vars = function() private$..vars$value,
        eps = function() private$..eps$value,
        minPts = function() private$..minPts$value,
        standardize = function() private$..standardize$value,
        dist = function() private$..dist$value,
        cm = function() private$..cm$value,
        sizeTable = function() private$..sizeTable$value,
        plot = function() private$..plot$value,
        profileTable = function() private$..profileTable$value,
        prostat = function() private$..prostat$value,
        knnPlot = function() private$..knnPlot$value,
        autoEps = function() private$..autoEps$value,
        epsQuantile = function() private$..epsQuantile$value,
        quality = function() private$..quality$value,
        qoption = function() private$..qoption$value,
        width = function() private$..width$value,
        height = function() private$..height$value,
        width1 = function() private$..width1$value,
        height1 = function() private$..height1$value),
    private = list(
        ..vars = NA,
        ..eps = NA,
        ..minPts = NA,
        ..standardize = NA,
        ..dist = NA,
        ..cm = NA,
        ..sizeTable = NA,
        ..plot = NA,
        ..profileTable = NA,
        ..prostat = NA,
        ..knnPlot = NA,
        ..autoEps = NA,
        ..epsQuantile = NA,
        ..quality = NA,
        ..qoption = NA,
        ..width = NA,
        ..height = NA,
        ..width1 = NA,
        ..height1 = NA)
)

dbscanResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "dbscanResults",
    inherit = jmvcore::Group,
    active = list(
        instructions = function() private$.items[["instructions"]],
        text = function() private$.items[["text"]],
        cm = function() private$.items[["cm"]],
        sizeTable = function() private$.items[["sizeTable"]],
        profileTable = function() private$.items[["profileTable"]],
        plot = function() private$.items[["plot"]],
        knnPlot = function() private$.items[["knnPlot"]],
        autoTable = function() private$.items[["autoTable"]],
        qualityTable = function() private$.items[["qualityTable"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Density-based Clustering",
                refs="snowCluster")
            self$add(jmvcore::Html$new(
                options=options,
                name="instructions",
                title="Instructions",
                visible=TRUE))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title=""))
            self$add(jmvcore::Output$new(
                options=options,
                name="cm",
                title="Cluster membership",
                varTitle="Membership",
                measureType="nominal",
                clearWith=list(
                    "vars",
                    "eps",
                    "minPts",
                    "dist",
                    "standardize")))
            self$add(jmvcore::Table$new(
                options=options,
                name="sizeTable",
                title="Cluster Sizes",
                rows=0,
                visible="(sizeTable)",
                refs="dbscan",
                clearWith=list(
                    "vars",
                    "eps",
                    "minPts",
                    "dist",
                    "standardize"),
                columns=list(
                    list(
                        `name`="cluster", 
                        `title`="Cluster", 
                        `type`="integer"),
                    list(
                        `name`="n", 
                        `title`="N", 
                        `type`="integer"),
                    list(
                        `name`="proportion", 
                        `title`="Proportion", 
                        `type`="number", 
                        `format`="zto.pct"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="profileTable",
                title="Cluster Profiles",
                rows=0,
                visible="(profileTable)",
                refs="dbscan",
                clearWith=list(
                    "vars",
                    "eps",
                    "minPts",
                    "dist",
                    "standardize",
                    "prostat"),
                columns=list(
                    list(
                        `name`="cluster", 
                        `title`="Cluster", 
                        `type`="integer"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="Cluster Plot",
                visible="(plot)",
                renderFun=".plot",
                refs="dbscan",
                clearWith=list(
                    "vars",
                    "eps",
                    "minPts",
                    "dist",
                    "standardize",
                    "autoEps",
                    "epsQuantile",
                    "width",
                    "height")))
            self$add(jmvcore::Image$new(
                options=options,
                name="knnPlot",
                title="kNN-distance Plot",
                width=520,
                height=360,
                visible="(knnPlot)",
                renderFun=".plotKNN",
                refs="dbscan",
                clearWith=list(
                    "vars",
                    "eps",
                    "minPts",
                    "dist",
                    "standardize",
                    "autoEps",
                    "epsQuantile",
                    "width1",
                    "height1")))
            self$add(jmvcore::Table$new(
                options=options,
                name="autoTable",
                title="Auto \u03B5 details",
                rows=0,
                visible="(autoEps)",
                refs="dbscan",
                clearWith=list(
                    "vars",
                    "eps",
                    "minPts",
                    "dist",
                    "standardize",
                    "autoEps",
                    "epsQuantile"),
                columns=list(
                    list(
                        `name`="eps_used", 
                        `title`="\u03B5 used", 
                        `type`="number"),
                    list(
                        `name`="quantile", 
                        `title`="Quantile", 
                        `type`="number", 
                        `format`="zto.pct"),
                    list(
                        `name`="k", 
                        `title`="k (minPts)", 
                        `type`="integer"),
                    list(
                        `name`="n", 
                        `title`="N", 
                        `type`="integer"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="qualityTable",
                title="Quality Indices",
                rows=0,
                visible="(quality)",
                refs="snowCluster",
                clearWith=list(
                    "vars",
                    "eps",
                    "minPts",
                    "dist",
                    "standardize",
                    "autoEps",
                    "epsQuantile",
                    "qoption"),
                columns=list(
                    list(
                        `name`="metric", 
                        `title`="Metric", 
                        `type`="text"),
                    list(
                        `name`="value", 
                        `title`="Value", 
                        `type`="number"))))}))

dbscanBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "dbscanBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "snowCluster",
                name = "dbscan",
                version = c(1,0,0),
                options = options,
                results = dbscanResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'none')
        }))

#' Density-based Clustering
#'
#' 
#' @param data .
#' @param vars .
#' @param eps .
#' @param minPts .
#' @param standardize .
#' @param dist .
#' @param sizeTable .
#' @param plot .
#' @param profileTable .
#' @param prostat .
#' @param knnPlot .
#' @param autoEps .
#' @param epsQuantile .
#' @param quality .
#' @param qoption .
#' @param width .
#' @param height .
#' @param width1 .
#' @param height1 .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$instructions} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$cm} \tab \tab \tab \tab \tab an output \cr
#'   \code{results$sizeTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$profileTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$knnPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$autoTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$qualityTable} \tab \tab \tab \tab \tab a table \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$sizeTable$asDF}
#'
#' \code{as.data.frame(results$sizeTable)}
#'
#' @export
dbscan <- function(
    data,
    vars,
    eps = 0.5,
    minPts = 5,
    standardize = FALSE,
    dist = "euclidean",
    sizeTable = FALSE,
    plot = FALSE,
    profileTable = FALSE,
    prostat = "mean",
    knnPlot = FALSE,
    autoEps = FALSE,
    epsQuantile = 0.95,
    quality = FALSE,
    qoption = "none",
    width = 500,
    height = 500,
    width1 = 500,
    height1 = 500) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("dbscan requires jmvcore to be installed (restart may be required)")

    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(vars), vars, NULL))


    options <- dbscanOptions$new(
        vars = vars,
        eps = eps,
        minPts = minPts,
        standardize = standardize,
        dist = dist,
        sizeTable = sizeTable,
        plot = plot,
        profileTable = profileTable,
        prostat = prostat,
        knnPlot = knnPlot,
        autoEps = autoEps,
        epsQuantile = epsQuantile,
        quality = quality,
        qoption = qoption,
        width = width,
        height = height,
        width1 = width1,
        height1 = height1)

    analysis <- dbscanClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

