
# This file is automatically generated, you probably don't want to edit this

discOptions <- if (requireNamespace('jmvcore')) R6::R6Class(
    "discOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            dep = NULL,
            covs = NULL,
            homo = FALSE,
            prior = FALSE,
            gm = FALSE,
            coef = FALSE,
            trace = FALSE,
            plot = FALSE, ...) {

            super$initialize(
                package='snowCluster',
                name='disc',
                requiresData=TRUE,
                ...)

            private$..dep <- jmvcore::OptionVariable$new(
                "dep",
                dep,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..covs <- jmvcore::OptionVariables$new(
                "covs",
                covs,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..homo <- jmvcore::OptionBool$new(
                "homo",
                homo,
                default=FALSE)
            private$..prior <- jmvcore::OptionBool$new(
                "prior",
                prior,
                default=FALSE)
            private$..gm <- jmvcore::OptionBool$new(
                "gm",
                gm,
                default=FALSE)
            private$..coef <- jmvcore::OptionBool$new(
                "coef",
                coef,
                default=FALSE)
            private$..trace <- jmvcore::OptionBool$new(
                "trace",
                trace,
                default=FALSE)
            private$..plot <- jmvcore::OptionBool$new(
                "plot",
                plot,
                default=FALSE)

            self$.addOption(private$..dep)
            self$.addOption(private$..covs)
            self$.addOption(private$..homo)
            self$.addOption(private$..prior)
            self$.addOption(private$..gm)
            self$.addOption(private$..coef)
            self$.addOption(private$..trace)
            self$.addOption(private$..plot)
        }),
    active = list(
        dep = function() private$..dep$value,
        covs = function() private$..covs$value,
        homo = function() private$..homo$value,
        prior = function() private$..prior$value,
        gm = function() private$..gm$value,
        coef = function() private$..coef$value,
        trace = function() private$..trace$value,
        plot = function() private$..plot$value),
    private = list(
        ..dep = NA,
        ..covs = NA,
        ..homo = NA,
        ..prior = NA,
        ..gm = NA,
        ..coef = NA,
        ..trace = NA,
        ..plot = NA)
)

discResults <- if (requireNamespace('jmvcore')) R6::R6Class(
    inherit = jmvcore::Group,
    active = list(
        instructions = function() private$.items[["instructions"]],
        text = function() private$.items[["text"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Linear Discriminant")
            self$add(jmvcore::Html$new(
                options=options,
                name="instructions",
                title="Instructions",
                visible=TRUE))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="Prior probabilities of groups"))}))

discBase <- if (requireNamespace('jmvcore')) R6::R6Class(
    "discBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = 'snowCluster',
                name = 'disc',
                version = c(1,0,0),
                options = options,
                results = discResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Linear Discriminant
#'
#' 
#' @param data .
#' @param dep .
#' @param covs .
#' @param homo .
#' @param prior .
#' @param gm .
#' @param coef .
#' @param trace .
#' @param plot .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$instructions} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#' }
#'
#' @export
disc <- function(
    data,
    dep,
    covs,
    homo = FALSE,
    prior = FALSE,
    gm = FALSE,
    coef = FALSE,
    trace = FALSE,
    plot = FALSE) {

    if ( ! requireNamespace('jmvcore'))
        stop('disc requires jmvcore to be installed (restart may be required)')

    if ( ! missing(dep)) dep <- jmvcore::resolveQuo(jmvcore::enquo(dep))
    if ( ! missing(covs)) covs <- jmvcore::resolveQuo(jmvcore::enquo(covs))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(dep), dep, NULL),
            `if`( ! missing(covs), covs, NULL))

    for (v in dep) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- discOptions$new(
        dep = dep,
        covs = covs,
        homo = homo,
        prior = prior,
        gm = gm,
        coef = coef,
        trace = trace,
        plot = plot)

    analysis <- discClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}
