
# This file is automatically generated, you probably don't want to edit this

famdOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "famdOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars = NULL,
            labels = NULL,
            eigen = TRUE,
            type1 = "coordinates",
            type2 = "coordinates",
            type3 = "coordinates",
            type4 = "coordinates",
            ind = FALSE,
            vari = FALSE,
            quan = FALSE,
            qual = FALSE,
            plot = TRUE,
            plot1 = FALSE,
            plot2 = FALSE,
            plot3 = FALSE,
            plot4 = FALSE,
            width = 500,
            height = 500,
            width1 = 500,
            height1 = 500,
            width2 = 500,
            height2 = 500,
            width3 = 500,
            height3 = 500,
            width4 = 500,
            height4 = 500, ...) {

            super$initialize(
                package="snowCluster",
                name="famd",
                requiresData=TRUE,
                ...)

            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars)
            private$..labels <- jmvcore::OptionVariable$new(
                "labels",
                labels,
                suggested=list(
                    "id"),
                permitted=list(
                    "id",
                    "factor"))
            private$..eigen <- jmvcore::OptionBool$new(
                "eigen",
                eigen,
                default=TRUE)
            private$..type1 <- jmvcore::OptionList$new(
                "type1",
                type1,
                options=list(
                    "coordinates",
                    "cos2",
                    "contribution"),
                default="coordinates")
            private$..type2 <- jmvcore::OptionList$new(
                "type2",
                type2,
                options=list(
                    "coordinates",
                    "cos2",
                    "contribution"),
                default="coordinates")
            private$..type3 <- jmvcore::OptionList$new(
                "type3",
                type3,
                options=list(
                    "coordinates",
                    "cos2",
                    "contribution"),
                default="coordinates")
            private$..type4 <- jmvcore::OptionList$new(
                "type4",
                type4,
                options=list(
                    "coordinates",
                    "cos2",
                    "contribution"),
                default="coordinates")
            private$..ind <- jmvcore::OptionBool$new(
                "ind",
                ind,
                default=FALSE)
            private$..vari <- jmvcore::OptionBool$new(
                "vari",
                vari,
                default=FALSE)
            private$..quan <- jmvcore::OptionBool$new(
                "quan",
                quan,
                default=FALSE)
            private$..qual <- jmvcore::OptionBool$new(
                "qual",
                qual,
                default=FALSE)
            private$..plot <- jmvcore::OptionBool$new(
                "plot",
                plot,
                default=TRUE)
            private$..plot1 <- jmvcore::OptionBool$new(
                "plot1",
                plot1,
                default=FALSE)
            private$..plot2 <- jmvcore::OptionBool$new(
                "plot2",
                plot2,
                default=FALSE)
            private$..plot3 <- jmvcore::OptionBool$new(
                "plot3",
                plot3,
                default=FALSE)
            private$..plot4 <- jmvcore::OptionBool$new(
                "plot4",
                plot4,
                default=FALSE)
            private$..width <- jmvcore::OptionInteger$new(
                "width",
                width,
                default=500)
            private$..height <- jmvcore::OptionInteger$new(
                "height",
                height,
                default=500)
            private$..width1 <- jmvcore::OptionInteger$new(
                "width1",
                width1,
                default=500)
            private$..height1 <- jmvcore::OptionInteger$new(
                "height1",
                height1,
                default=500)
            private$..width2 <- jmvcore::OptionInteger$new(
                "width2",
                width2,
                default=500)
            private$..height2 <- jmvcore::OptionInteger$new(
                "height2",
                height2,
                default=500)
            private$..width3 <- jmvcore::OptionInteger$new(
                "width3",
                width3,
                default=500)
            private$..height3 <- jmvcore::OptionInteger$new(
                "height3",
                height3,
                default=500)
            private$..width4 <- jmvcore::OptionInteger$new(
                "width4",
                width4,
                default=500)
            private$..height4 <- jmvcore::OptionInteger$new(
                "height4",
                height4,
                default=500)

            self$.addOption(private$..vars)
            self$.addOption(private$..labels)
            self$.addOption(private$..eigen)
            self$.addOption(private$..type1)
            self$.addOption(private$..type2)
            self$.addOption(private$..type3)
            self$.addOption(private$..type4)
            self$.addOption(private$..ind)
            self$.addOption(private$..vari)
            self$.addOption(private$..quan)
            self$.addOption(private$..qual)
            self$.addOption(private$..plot)
            self$.addOption(private$..plot1)
            self$.addOption(private$..plot2)
            self$.addOption(private$..plot3)
            self$.addOption(private$..plot4)
            self$.addOption(private$..width)
            self$.addOption(private$..height)
            self$.addOption(private$..width1)
            self$.addOption(private$..height1)
            self$.addOption(private$..width2)
            self$.addOption(private$..height2)
            self$.addOption(private$..width3)
            self$.addOption(private$..height3)
            self$.addOption(private$..width4)
            self$.addOption(private$..height4)
        }),
    active = list(
        vars = function() private$..vars$value,
        labels = function() private$..labels$value,
        eigen = function() private$..eigen$value,
        type1 = function() private$..type1$value,
        type2 = function() private$..type2$value,
        type3 = function() private$..type3$value,
        type4 = function() private$..type4$value,
        ind = function() private$..ind$value,
        vari = function() private$..vari$value,
        quan = function() private$..quan$value,
        qual = function() private$..qual$value,
        plot = function() private$..plot$value,
        plot1 = function() private$..plot1$value,
        plot2 = function() private$..plot2$value,
        plot3 = function() private$..plot3$value,
        plot4 = function() private$..plot4$value,
        width = function() private$..width$value,
        height = function() private$..height$value,
        width1 = function() private$..width1$value,
        height1 = function() private$..height1$value,
        width2 = function() private$..width2$value,
        height2 = function() private$..height2$value,
        width3 = function() private$..width3$value,
        height3 = function() private$..height3$value,
        width4 = function() private$..width4$value,
        height4 = function() private$..height4$value),
    private = list(
        ..vars = NA,
        ..labels = NA,
        ..eigen = NA,
        ..type1 = NA,
        ..type2 = NA,
        ..type3 = NA,
        ..type4 = NA,
        ..ind = NA,
        ..vari = NA,
        ..quan = NA,
        ..qual = NA,
        ..plot = NA,
        ..plot1 = NA,
        ..plot2 = NA,
        ..plot3 = NA,
        ..plot4 = NA,
        ..width = NA,
        ..height = NA,
        ..width1 = NA,
        ..height1 = NA,
        ..width2 = NA,
        ..height2 = NA,
        ..width3 = NA,
        ..height3 = NA,
        ..width4 = NA,
        ..height4 = NA)
)

famdResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "famdResults",
    inherit = jmvcore::Group,
    active = list(
        instructions = function() private$.items[["instructions"]],
        eigen = function() private$.items[["eigen"]],
        ind = function() private$.items[["ind"]],
        vari = function() private$.items[["vari"]],
        quan = function() private$.items[["quan"]],
        qual = function() private$.items[["qual"]],
        plot = function() private$.items[["plot"]],
        plot1 = function() private$.items[["plot1"]],
        plot2 = function() private$.items[["plot2"]],
        plot3 = function() private$.items[["plot3"]],
        plot4 = function() private$.items[["plot4"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Factor analysis of mixed data",
                refs="snowCluster")
            self$add(jmvcore::Html$new(
                options=options,
                name="instructions",
                title="Instructions",
                visible=TRUE))
            self$add(jmvcore::Table$new(
                options=options,
                name="eigen",
                title="Eigenvalues",
                visible="(eigen)",
                clearWith=list(
                    "vars",
                    "labels"),
                columns=list(
                    list(
                        `name`="comp", 
                        `title`="Component", 
                        `type`="text"),
                    list(
                        `name`="eigen", 
                        `title`="Eigenvalue", 
                        `type`="number"),
                    list(
                        `name`="varProp", 
                        `title`="% of Variance", 
                        `type`="number"),
                    list(
                        `name`="varCum", 
                        `title`="Cumulative %", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="ind",
                title="`Individuals across dimensions - ${type1}`",
                visible="(ind)",
                clearWith=list(
                    "vars",
                    "labels",
                    "type1"),
                columns=list(
                    list(
                        `name`="name", 
                        `title`="", 
                        `type`="text", 
                        `content`="($key)"),
                    list(
                        `name`="pc1", 
                        `title`="1", 
                        `type`="number", 
                        `superTitle`="Dimension"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="vari",
                title="`Variables across dimensions - ${type2}`",
                visible="(vari)",
                clearWith=list(
                    "vars",
                    "labels",
                    "type2"),
                columns=list(
                    list(
                        `name`="name", 
                        `title`="", 
                        `type`="text", 
                        `content`="($key)"),
                    list(
                        `name`="pc1", 
                        `title`="1", 
                        `type`="number", 
                        `superTitle`="Dimension"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="quan",
                title="`Quantitative variables across dimensions - ${type3}`",
                visible="(quan)",
                clearWith=list(
                    "vars",
                    "labels",
                    "type3"),
                columns=list(
                    list(
                        `name`="name", 
                        `title`="", 
                        `type`="text", 
                        `content`="($key)"),
                    list(
                        `name`="pc1", 
                        `title`="1", 
                        `type`="number", 
                        `superTitle`="Dimension"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="qual",
                title="`Qualitative variables across dimensions - ${type4}`",
                visible="(qual)",
                clearWith=list(
                    "vars",
                    "labels",
                    "type4"),
                columns=list(
                    list(
                        `name`="name", 
                        `title`="", 
                        `type`="text", 
                        `content`="($key)"),
                    list(
                        `name`="pc1", 
                        `title`="1", 
                        `type`="number", 
                        `superTitle`="Dimension"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="Scree plot",
                refs="factoextra",
                visible="(plot)",
                renderFun=".plot",
                clearWith=list(
                    "vars",
                    "labels",
                    "width",
                    "height")))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot1",
                title="Graph of variables",
                refs="factoextra",
                visible="(plot1)",
                renderFun=".plot1",
                clearWith=list(
                    "vars",
                    "labels",
                    "type2",
                    "width1",
                    "height1")))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot2",
                title="Quantitative variables",
                refs="factoextra",
                visible="(plot2)",
                renderFun=".plot2",
                clearWith=list(
                    "vars",
                    "labels",
                    "type3",
                    "width2",
                    "height2")))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot3",
                title="Qualitative variables",
                refs="factoextra",
                visible="(plot3)",
                renderFun=".plot3",
                clearWith=list(
                    "vars",
                    "labels",
                    "type4",
                    "width3",
                    "height3")))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot4",
                title="Graph of individuals",
                refs="factoextra",
                visible="(plot4)",
                renderFun=".plot4",
                clearWith=list(
                    "vars",
                    "labels",
                    "type1",
                    "width4",
                    "height4")))}))

famdBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "famdBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "snowCluster",
                name = "famd",
                version = c(1,0,0),
                options = options,
                results = famdResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Factor analysis of mixed data
#'
#' 
#' @param data .
#' @param vars .
#' @param labels .
#' @param eigen .
#' @param type1 .
#' @param type2 .
#' @param type3 .
#' @param type4 .
#' @param ind .
#' @param vari .
#' @param quan .
#' @param qual .
#' @param plot .
#' @param plot1 .
#' @param plot2 .
#' @param plot3 .
#' @param plot4 .
#' @param width .
#' @param height .
#' @param width1 .
#' @param height1 .
#' @param width2 .
#' @param height2 .
#' @param width3 .
#' @param height3 .
#' @param width4 .
#' @param height4 .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$instructions} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$eigen} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$ind} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$vari} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$quan} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$qual} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plot1} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plot2} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plot3} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plot4} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$eigen$asDF}
#'
#' \code{as.data.frame(results$eigen)}
#'
#' @export
famd <- function(
    data,
    vars,
    labels,
    eigen = TRUE,
    type1 = "coordinates",
    type2 = "coordinates",
    type3 = "coordinates",
    type4 = "coordinates",
    ind = FALSE,
    vari = FALSE,
    quan = FALSE,
    qual = FALSE,
    plot = TRUE,
    plot1 = FALSE,
    plot2 = FALSE,
    plot3 = FALSE,
    plot4 = FALSE,
    width = 500,
    height = 500,
    width1 = 500,
    height1 = 500,
    width2 = 500,
    height2 = 500,
    width3 = 500,
    height3 = 500,
    width4 = 500,
    height4 = 500) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("famd requires jmvcore to be installed (restart may be required)")

    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if ( ! missing(labels)) labels <- jmvcore::resolveQuo(jmvcore::enquo(labels))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(vars), vars, NULL),
            `if`( ! missing(labels), labels, NULL))


    options <- famdOptions$new(
        vars = vars,
        labels = labels,
        eigen = eigen,
        type1 = type1,
        type2 = type2,
        type3 = type3,
        type4 = type4,
        ind = ind,
        vari = vari,
        quan = quan,
        qual = qual,
        plot = plot,
        plot1 = plot1,
        plot2 = plot2,
        plot3 = plot3,
        plot4 = plot4,
        width = width,
        height = height,
        width1 = width1,
        height1 = height1,
        width2 = width2,
        height2 = height2,
        width3 = width3,
        height3 = height3,
        width4 = width4,
        height4 = height4)

    analysis <- famdClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

