
# This file is automatically generated, you probably don't want to edit this

groupOptions <- if (requireNamespace('jmvcore')) R6::R6Class(
    "groupOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            facs = NULL,
            vars = NULL,
            plot = TRUE,
            plot1 = FALSE, ...) {

            super$initialize(
                package='snowCluster',
                name='group',
                requiresData=TRUE,
                ...)

            private$..facs <- jmvcore::OptionVariable$new(
                "facs",
                facs,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..plot <- jmvcore::OptionBool$new(
                "plot",
                plot,
                default=TRUE)
            private$..plot1 <- jmvcore::OptionBool$new(
                "plot1",
                plot1,
                default=FALSE)

            self$.addOption(private$..facs)
            self$.addOption(private$..vars)
            self$.addOption(private$..plot)
            self$.addOption(private$..plot1)
        }),
    active = list(
        facs = function() private$..facs$value,
        vars = function() private$..vars$value,
        plot = function() private$..plot$value,
        plot1 = function() private$..plot1$value),
    private = list(
        ..facs = NA,
        ..vars = NA,
        ..plot = NA,
        ..plot1 = NA)
)

groupResults <- if (requireNamespace('jmvcore')) R6::R6Class(
    inherit = jmvcore::Group,
    active = list(
        plot = function() private$.items[["plot"]],
        plot1 = function() private$.items[["plot1"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Group plot",
                refs="snowCluster")
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="Individuals by groups",
                requiresData=TRUE,
                refs="factoextra",
                visible="(plot)",
                width=500,
                height=500,
                renderFun=".plot"))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot1",
                title="PCA-Biplot",
                requiresData=TRUE,
                refs="factoextra",
                visible="(plot1)",
                width=500,
                height=500,
                renderFun=".plot1"))}))

groupBase <- if (requireNamespace('jmvcore')) R6::R6Class(
    "groupBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = 'snowCluster',
                name = 'group',
                version = c(1,0,0),
                options = options,
                results = groupResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Group plot
#'
#' 
#' @param data The data as a data frame.
#' @param facs .
#' @param vars .
#' @param plot .
#' @param plot1 .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plot1} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' @export
group <- function(
    data,
    facs,
    vars,
    plot = TRUE,
    plot1 = FALSE) {

    if ( ! requireNamespace('jmvcore'))
        stop('group requires jmvcore to be installed (restart may be required)')

    if ( ! missing(facs)) facs <- jmvcore::resolveQuo(jmvcore::enquo(facs))
    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(facs), facs, NULL),
            `if`( ! missing(vars), vars, NULL))

    for (v in facs) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- groupOptions$new(
        facs = facs,
        vars = vars,
        plot = plot,
        plot1 = plot1)

    analysis <- groupClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}
