
# This file is automatically generated, you probably don't want to edit this

hcOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "hcOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            labels = NULL,
            vars = NULL,
            stand = TRUE,
            k = 2,
            metric = "euclidean",
            method = "ward.D2",
            type = "rectangle",
            plot = TRUE, ...) {

            super$initialize(
                package="snowCluster",
                name="hc",
                requiresData=TRUE,
                ...)

            private$..labels <- jmvcore::OptionVariable$new(
                "labels",
                labels,
                suggested=list(
                    "id"),
                permitted=list(
                    "id",
                    "factor"))
            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..stand <- jmvcore::OptionBool$new(
                "stand",
                stand,
                default=TRUE)
            private$..k <- jmvcore::OptionInteger$new(
                "k",
                k,
                default=2,
                min=1)
            private$..metric <- jmvcore::OptionList$new(
                "metric",
                metric,
                options=list(
                    "euclidean",
                    "manhattan",
                    "maximum",
                    "canberra",
                    "binary",
                    "minkowski"),
                default="euclidean")
            private$..method <- jmvcore::OptionList$new(
                "method",
                method,
                options=list(
                    "ward.D",
                    "ward.D2",
                    "single",
                    "complete",
                    "average"),
                default="ward.D2")
            private$..type <- jmvcore::OptionList$new(
                "type",
                type,
                options=list(
                    "rectangle",
                    "circular",
                    "phylogenic"),
                default="rectangle")
            private$..plot <- jmvcore::OptionBool$new(
                "plot",
                plot,
                default=TRUE)
            private$..clust <- jmvcore::OptionOutput$new(
                "clust")

            self$.addOption(private$..labels)
            self$.addOption(private$..vars)
            self$.addOption(private$..stand)
            self$.addOption(private$..k)
            self$.addOption(private$..metric)
            self$.addOption(private$..method)
            self$.addOption(private$..type)
            self$.addOption(private$..plot)
            self$.addOption(private$..clust)
        }),
    active = list(
        labels = function() private$..labels$value,
        vars = function() private$..vars$value,
        stand = function() private$..stand$value,
        k = function() private$..k$value,
        metric = function() private$..metric$value,
        method = function() private$..method$value,
        type = function() private$..type$value,
        plot = function() private$..plot$value,
        clust = function() private$..clust$value),
    private = list(
        ..labels = NA,
        ..vars = NA,
        ..stand = NA,
        ..k = NA,
        ..metric = NA,
        ..method = NA,
        ..type = NA,
        ..plot = NA,
        ..clust = NA)
)

hcResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "hcResults",
    inherit = jmvcore::Group,
    active = list(
        instructions = function() private$.items[["instructions"]],
        clust = function() private$.items[["clust"]],
        plot = function() private$.items[["plot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Clustering Dendrogram",
                refs="snowCluster")
            self$add(jmvcore::Html$new(
                options=options,
                name="instructions",
                title="Instructions",
                visible=TRUE))
            self$add(jmvcore::Output$new(
                options=options,
                name="clust",
                title="Clustering",
                varTitle="Clustering",
                measureType="nominal",
                clearWith=list(
                    "vars",
                    "k",
                    "stand",
                    "metric",
                    "type",
                    "method")))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="Cluster Dendrogram",
                requiresData=TRUE,
                refs="factoextra",
                visible="(plot)",
                width=500,
                height=500,
                renderFun=".plot",
                clearWith=list(
                    "vars",
                    "k",
                    "stand",
                    "metric",
                    "type",
                    "method")))}))

hcBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "hcBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "snowCluster",
                name = "hc",
                version = c(1,0,0),
                options = options,
                results = hcResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'none')
        }))

#' Clustering Dendrogram
#'
#' 
#' @param data The data as a data frame.
#' @param labels .
#' @param vars .
#' @param stand .
#' @param k .
#' @param metric .
#' @param method .
#' @param type .
#' @param plot .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$instructions} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$clust} \tab \tab \tab \tab \tab an output \cr
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' @export
hc <- function(
    data,
    labels,
    vars,
    stand = TRUE,
    k = 2,
    metric = "euclidean",
    method = "ward.D2",
    type = "rectangle",
    plot = TRUE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("hc requires jmvcore to be installed (restart may be required)")

    if ( ! missing(labels)) labels <- jmvcore::resolveQuo(jmvcore::enquo(labels))
    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(labels), labels, NULL),
            `if`( ! missing(vars), vars, NULL))


    options <- hcOptions$new(
        labels = labels,
        vars = vars,
        stand = stand,
        k = k,
        metric = metric,
        method = method,
        type = type,
        plot = plot)

    analysis <- hcClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

