
# This file is automatically generated, you probably don't want to edit this

kmeansOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "kmeansOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars = NULL,
            k = 2,
            algo = "Hartigan-Wong",
            nstart = 10,
            stand = FALSE,
            plot = TRUE,
            angle = 0,
            plot1 = FALSE,
            plot2 = FALSE,
            plot3 = FALSE, ...) {

            super$initialize(
                package="snowCluster",
                name="kmeans",
                requiresData=TRUE,
                ...)

            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..k <- jmvcore::OptionInteger$new(
                "k",
                k,
                default=2,
                min=1)
            private$..algo <- jmvcore::OptionList$new(
                "algo",
                algo,
                options=list(
                    "Hartigan-Wong",
                    "Lloyd",
                    "Forgy",
                    "MacQueen"),
                default="Hartigan-Wong")
            private$..nstart <- jmvcore::OptionInteger$new(
                "nstart",
                nstart,
                default=10)
            private$..stand <- jmvcore::OptionBool$new(
                "stand",
                stand,
                default=FALSE)
            private$..plot <- jmvcore::OptionBool$new(
                "plot",
                plot,
                default=TRUE)
            private$..angle <- jmvcore::OptionNumber$new(
                "angle",
                angle,
                min=0,
                max=90,
                default=0)
            private$..plot1 <- jmvcore::OptionBool$new(
                "plot1",
                plot1,
                default=FALSE)
            private$..plot2 <- jmvcore::OptionBool$new(
                "plot2",
                plot2,
                default=FALSE)
            private$..plot3 <- jmvcore::OptionBool$new(
                "plot3",
                plot3,
                default=FALSE)
            private$..clust <- jmvcore::OptionOutput$new(
                "clust")

            self$.addOption(private$..vars)
            self$.addOption(private$..k)
            self$.addOption(private$..algo)
            self$.addOption(private$..nstart)
            self$.addOption(private$..stand)
            self$.addOption(private$..plot)
            self$.addOption(private$..angle)
            self$.addOption(private$..plot1)
            self$.addOption(private$..plot2)
            self$.addOption(private$..plot3)
            self$.addOption(private$..clust)
        }),
    active = list(
        vars = function() private$..vars$value,
        k = function() private$..k$value,
        algo = function() private$..algo$value,
        nstart = function() private$..nstart$value,
        stand = function() private$..stand$value,
        plot = function() private$..plot$value,
        angle = function() private$..angle$value,
        plot1 = function() private$..plot1$value,
        plot2 = function() private$..plot2$value,
        plot3 = function() private$..plot3$value,
        clust = function() private$..clust$value),
    private = list(
        ..vars = NA,
        ..k = NA,
        ..algo = NA,
        ..nstart = NA,
        ..stand = NA,
        ..plot = NA,
        ..angle = NA,
        ..plot1 = NA,
        ..plot2 = NA,
        ..plot3 = NA,
        ..clust = NA)
)

kmeansResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "kmeansResults",
    inherit = jmvcore::Group,
    active = list(
        instructions = function() private$.items[["instructions"]],
        text = function() private$.items[["text"]],
        ss = function() private$.items[["ss"]],
        clustering = function() private$.items[["clustering"]],
        centroids = function() private$.items[["centroids"]],
        plot = function() private$.items[["plot"]],
        plot1 = function() private$.items[["plot1"]],
        plot2 = function() private$.items[["plot2"]],
        plot3 = function() private$.items[["plot3"]],
        clust = function() private$.items[["clust"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="K-means Clustering",
                refs="snowCluster")
            self$add(jmvcore::Html$new(
                options=options,
                name="instructions",
                title="Instructions",
                visible=TRUE))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="Clustering vector"))
            self$add(jmvcore::Table$new(
                options=options,
                name="ss",
                title="Sum of squares Table",
                rows=0,
                refs="snowCluster",
                clearWith=list(
                    "vars",
                    "k",
                    "algo",
                    "nstart",
                    "stand"),
                columns=list(
                    list(
                        `name`="source", 
                        `title`="", 
                        `type`="text"),
                    list(
                        `name`="value", 
                        `title`="Value"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="clustering",
                title="Clustering Table",
                clearWith=list(
                    "vars",
                    "k",
                    "algo",
                    "nstart",
                    "stand"),
                refs="snowCluster",
                columns=list(
                    list(
                        `name`="cluster", 
                        `title`="Cluster No", 
                        `type`="text"),
                    list(
                        `name`="count", 
                        `title`="Count", 
                        `type`="integer"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="centroids",
                title="Centroids of clusters Table",
                rows="(k)",
                clearWith=list(
                    "vars",
                    "k",
                    "algo",
                    "nstart",
                    "stand"),
                refs="snowCluster",
                columns=list(
                    list(
                        `name`=".name[x]", 
                        `title`="", 
                        `type`="text", 
                        `content`="($key)"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="Plot of means across clusters",
                visible="(plot)",
                width=700,
                height=500,
                renderFun=".plot",
                clearWith=list(
                    "vars",
                    "k",
                    "algo",
                    "nstart",
                    "stand",
                    "angle")))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot1",
                title="Optimal number of clusters",
                refs="factoextra",
                visible="(plot1)",
                width=500,
                height=500,
                renderFun=".plot1",
                clearWith=list(
                    "vars",
                    "k",
                    "algo",
                    "nstart",
                    "stand")))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot2",
                title="Cluster plot",
                requiresData=TRUE,
                refs="factoextra",
                visible="(plot2)",
                width=500,
                height=500,
                renderFun=".plot2",
                clearWith=list(
                    "vars",
                    "k",
                    "algo",
                    "nstart",
                    "stand")))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot3",
                title="Variables-PCA",
                requiresData=TRUE,
                refs="factoextra",
                visible="(plot3)",
                width=500,
                height=500,
                renderFun=".plot3",
                clearWith=list(
                    "vars",
                    "k",
                    "algo",
                    "nstart",
                    "stand")))
            self$add(jmvcore::Output$new(
                options=options,
                name="clust",
                title="Clustering",
                varTitle="Clustering",
                measureType="nominal",
                clearWith=list(
                    "vars",
                    "k",
                    "algo",
                    "nstart",
                    "stand")))}))

kmeansBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "kmeansBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "snowCluster",
                name = "kmeans",
                version = c(1,0,0),
                options = options,
                results = kmeansResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'none')
        }))

#' K-means Clustering
#'
#' 
#' @param data The data as a data frame.
#' @param vars .
#' @param k .
#' @param algo .
#' @param nstart .
#' @param stand .
#' @param plot .
#' @param angle a number from 0 to 90 defining the angle of the x-axis labels,
#'   where 0 degrees represents completely horizontal labels.
#' @param plot1 .
#' @param plot2 .
#' @param plot3 .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$instructions} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$ss} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$clustering} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$centroids} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plot1} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plot2} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plot3} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$clust} \tab \tab \tab \tab \tab an output \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$ss$asDF}
#'
#' \code{as.data.frame(results$ss)}
#'
#' @export
kmeans <- function(
    data,
    vars,
    k = 2,
    algo = "Hartigan-Wong",
    nstart = 10,
    stand = FALSE,
    plot = TRUE,
    angle = 0,
    plot1 = FALSE,
    plot2 = FALSE,
    plot3 = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("kmeans requires jmvcore to be installed (restart may be required)")

    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(vars), vars, NULL))


    options <- kmeansOptions$new(
        vars = vars,
        k = k,
        algo = algo,
        nstart = nstart,
        stand = stand,
        plot = plot,
        angle = angle,
        plot1 = plot1,
        plot2 = plot2,
        plot3 = plot3)

    analysis <- kmeansClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

