
# This file is automatically generated, you probably don't want to edit this

mcaOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "mcaOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            facs = NULL,
            vars = NULL,
            eigen = TRUE,
            rowvar = "coord",
            loadingind = FALSE,
            colvar = "coord",
            loadingvar = FALSE,
            plot1 = TRUE,
            plot2 = FALSE,
            plot3 = FALSE,
            plot4 = FALSE,
            plot5 = FALSE, ...) {

            super$initialize(
                package="snowCluster",
                name="mca",
                requiresData=TRUE,
                ...)

            private$..facs <- jmvcore::OptionVariable$new(
                "facs",
                facs,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..eigen <- jmvcore::OptionBool$new(
                "eigen",
                eigen,
                default=TRUE)
            private$..rowvar <- jmvcore::OptionList$new(
                "rowvar",
                rowvar,
                options=list(
                    "coord",
                    "cos2",
                    "contrib"),
                default="coord")
            private$..loadingind <- jmvcore::OptionBool$new(
                "loadingind",
                loadingind,
                default=FALSE)
            private$..colvar <- jmvcore::OptionList$new(
                "colvar",
                colvar,
                options=list(
                    "coord",
                    "cos2",
                    "contrib"),
                default="coord")
            private$..loadingvar <- jmvcore::OptionBool$new(
                "loadingvar",
                loadingvar,
                default=FALSE)
            private$..plot1 <- jmvcore::OptionBool$new(
                "plot1",
                plot1,
                default=TRUE)
            private$..plot2 <- jmvcore::OptionBool$new(
                "plot2",
                plot2,
                default=FALSE)
            private$..plot3 <- jmvcore::OptionBool$new(
                "plot3",
                plot3,
                default=FALSE)
            private$..plot4 <- jmvcore::OptionBool$new(
                "plot4",
                plot4,
                default=FALSE)
            private$..plot5 <- jmvcore::OptionBool$new(
                "plot5",
                plot5,
                default=FALSE)

            self$.addOption(private$..facs)
            self$.addOption(private$..vars)
            self$.addOption(private$..eigen)
            self$.addOption(private$..rowvar)
            self$.addOption(private$..loadingind)
            self$.addOption(private$..colvar)
            self$.addOption(private$..loadingvar)
            self$.addOption(private$..plot1)
            self$.addOption(private$..plot2)
            self$.addOption(private$..plot3)
            self$.addOption(private$..plot4)
            self$.addOption(private$..plot5)
        }),
    active = list(
        facs = function() private$..facs$value,
        vars = function() private$..vars$value,
        eigen = function() private$..eigen$value,
        rowvar = function() private$..rowvar$value,
        loadingind = function() private$..loadingind$value,
        colvar = function() private$..colvar$value,
        loadingvar = function() private$..loadingvar$value,
        plot1 = function() private$..plot1$value,
        plot2 = function() private$..plot2$value,
        plot3 = function() private$..plot3$value,
        plot4 = function() private$..plot4$value,
        plot5 = function() private$..plot5$value),
    private = list(
        ..facs = NA,
        ..vars = NA,
        ..eigen = NA,
        ..rowvar = NA,
        ..loadingind = NA,
        ..colvar = NA,
        ..loadingvar = NA,
        ..plot1 = NA,
        ..plot2 = NA,
        ..plot3 = NA,
        ..plot4 = NA,
        ..plot5 = NA)
)

mcaResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "mcaResults",
    inherit = jmvcore::Group,
    active = list(
        eigen = function() private$.items[["eigen"]],
        loadingvar = function() private$.items[["loadingvar"]],
        loadingind = function() private$.items[["loadingind"]],
        plot5 = function() private$.items[["plot5"]],
        plot1 = function() private$.items[["plot1"]],
        plot2 = function() private$.items[["plot2"]],
        plot3 = function() private$.items[["plot3"]],
        plot4 = function() private$.items[["plot4"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Multiple Correspondence Analysis",
                refs="snowCluster")
            self$add(jmvcore::Table$new(
                options=options,
                name="eigen",
                title="Eigenvalues",
                visible="(eigen)",
                clearWith=list(
                    "vars",
                    "rowvar",
                    "colvar"),
                columns=list(
                    list(
                        `name`="comp", 
                        `title`="Component", 
                        `type`="text"),
                    list(
                        `name`="eigen", 
                        `title`="Eigenvalue", 
                        `type`="number"),
                    list(
                        `name`="varProp", 
                        `title`="% of Variance", 
                        `type`="number"),
                    list(
                        `name`="varCum", 
                        `title`="Cumulative %", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="loadingvar",
                title="Variable categories across dimensions",
                visible="(loadingvar)",
                clearWith=list(
                    "vars",
                    "rowvar",
                    "colvar"),
                columns=list(
                    list(
                        `name`="name", 
                        `title`="", 
                        `type`="text", 
                        `content`="($key)"),
                    list(
                        `name`="pc1", 
                        `title`="1", 
                        `type`="number", 
                        `superTitle`="Dimension"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="loadingind",
                title="Observations across dimensions",
                visible="(loadingind)",
                clearWith=list(
                    "vars",
                    "rowvar",
                    "colvar"),
                columns=list(
                    list(
                        `name`="name", 
                        `title`="", 
                        `type`="text", 
                        `content`="($key)"),
                    list(
                        `name`="pc1", 
                        `title`="1", 
                        `type`="number", 
                        `superTitle`="Dimension"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot5",
                title="Scree plot",
                requiresData=TRUE,
                refs="factoextra",
                visible="(plot5)",
                width=500,
                height=500,
                renderFun=".plot5"))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot1",
                title="Correlation between variables and dimensions",
                requiresData=TRUE,
                refs="factoextra",
                visible="(plot1)",
                width=500,
                height=500,
                renderFun=".plot1"))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot2",
                title="Coordinates of variable categories",
                requiresData=TRUE,
                refs="factoextra",
                visible="(plot2)",
                width=500,
                height=500,
                renderFun=".plot2"))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot3",
                title="Plot of individuals",
                requiresData=TRUE,
                refs="factoextra",
                visible="(plot3)",
                width=500,
                height=500,
                renderFun=".plot3"))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot4",
                title="Individuals by groups",
                requiresData=TRUE,
                refs="factoextra",
                visible="(plot4)",
                width=500,
                height=500,
                renderFun=".plot4"))}))

mcaBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "mcaBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "snowCluster",
                name = "mca",
                version = c(1,0,0),
                options = options,
                results = mcaResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Multiple Correspondence Analysis
#'
#' 
#' @param data The data as a data frame.
#' @param facs .
#' @param vars .
#' @param eigen .
#' @param rowvar .
#' @param loadingind .
#' @param colvar .
#' @param loadingvar .
#' @param plot1 .
#' @param plot2 .
#' @param plot3 .
#' @param plot4 .
#' @param plot5 .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$eigen} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$loadingvar} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$loadingind} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$plot5} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plot1} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plot2} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plot3} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plot4} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$eigen$asDF}
#'
#' \code{as.data.frame(results$eigen)}
#'
#' @export
mca <- function(
    data,
    facs,
    vars,
    eigen = TRUE,
    rowvar = "coord",
    loadingind = FALSE,
    colvar = "coord",
    loadingvar = FALSE,
    plot1 = TRUE,
    plot2 = FALSE,
    plot3 = FALSE,
    plot4 = FALSE,
    plot5 = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("mca requires jmvcore to be installed (restart may be required)")

    if ( ! missing(facs)) facs <- jmvcore::resolveQuo(jmvcore::enquo(facs))
    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(facs), facs, NULL),
            `if`( ! missing(vars), vars, NULL))

    for (v in facs) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in vars) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- mcaOptions$new(
        facs = facs,
        vars = vars,
        eigen = eigen,
        rowvar = rowvar,
        loadingind = loadingind,
        colvar = colvar,
        loadingvar = loadingvar,
        plot1 = plot1,
        plot2 = plot2,
        plot3 = plot3,
        plot4 = plot4,
        plot5 = plot5)

    analysis <- mcaClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

