
# This file is automatically generated, you probably don't want to edit this

mdsOptions <- if (requireNamespace('jmvcore', quietly=TRUE)) R6::R6Class(
    "mdsOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            labels = NULL,
            vars = NULL,
            k = 2,
            plot = FALSE,
            plot1 = FALSE, ...) {

            super$initialize(
                package='snowCluster',
                name='mds',
                requiresData=TRUE,
                ...)

            private$..labels <- jmvcore::OptionVariable$new(
                "labels",
                labels,
                suggested=list(
                    "id"),
                permitted=list(
                    "id",
                    "factor"))
            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..k <- jmvcore::OptionInteger$new(
                "k",
                k,
                default=2,
                min=1)
            private$..plot <- jmvcore::OptionBool$new(
                "plot",
                plot,
                default=FALSE)
            private$..plot1 <- jmvcore::OptionBool$new(
                "plot1",
                plot1,
                default=FALSE)

            self$.addOption(private$..labels)
            self$.addOption(private$..vars)
            self$.addOption(private$..k)
            self$.addOption(private$..plot)
            self$.addOption(private$..plot1)
        }),
    active = list(
        labels = function() private$..labels$value,
        vars = function() private$..vars$value,
        k = function() private$..k$value,
        plot = function() private$..plot$value,
        plot1 = function() private$..plot1$value),
    private = list(
        ..labels = NA,
        ..vars = NA,
        ..k = NA,
        ..plot = NA,
        ..plot1 = NA)
)

mdsResults <- if (requireNamespace('jmvcore', quietly=TRUE)) R6::R6Class(
    inherit = jmvcore::Group,
    active = list(
        instructions = function() private$.items[["instructions"]],
        plot = function() private$.items[["plot"]],
        plot1 = function() private$.items[["plot1"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Multidimensional Scaling Plot")
            self$add(jmvcore::Html$new(
                options=options,
                name="instructions",
                title="Instructions",
                visible=TRUE))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="MDS Plot",
                requiresData=TRUE,
                visible="(plot)",
                width=500,
                height=500,
                renderFun=".plot",
                clearWith=list(
                    "vars")))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot1",
                title="K-means Plot",
                requiresData=TRUE,
                visible="(plot1)",
                width=500,
                height=500,
                renderFun=".plot1",
                clearWith=list(
                    "vars",
                    "k")))}))

mdsBase <- if (requireNamespace('jmvcore', quietly=TRUE)) R6::R6Class(
    "mdsBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = 'snowCluster',
                name = 'mds',
                version = c(1,0,0),
                options = options,
                results = mdsResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Multidimensional Scaling Plot
#'
#' 
#' @param data The data as a data frame.
#' @param labels .
#' @param vars .
#' @param k .
#' @param plot .
#' @param plot1 .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$instructions} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plot1} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' @export
mds <- function(
    data,
    labels,
    vars,
    k = 2,
    plot = FALSE,
    plot1 = FALSE) {

    if ( ! requireNamespace('jmvcore', quietly=TRUE))
        stop('mds requires jmvcore to be installed (restart may be required)')

    if ( ! missing(labels)) labels <- jmvcore::resolveQuo(jmvcore::enquo(labels))
    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(labels), labels, NULL),
            `if`( ! missing(vars), vars, NULL))


    options <- mdsOptions$new(
        labels = labels,
        vars = vars,
        k = k,
        plot = plot,
        plot1 = plot1)

    analysis <- mdsClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

