
# This file is automatically generated, you probably don't want to edit this

mdsOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "mdsOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            mode = "simple",
            labels = NULL,
            vars = NULL,
            k = 2,
            plot = FALSE,
            plot1 = FALSE,
            stress = FALSE,
            plot3 = FALSE,
            xlab = NULL,
            ylab = NULL,
            zlab = NULL,
            plot2 = FALSE,
            metric = "euclidean", ...) {

            super$initialize(
                package="snowCluster",
                name="mds",
                requiresData=TRUE,
                ...)

            private$..mode <- jmvcore::OptionList$new(
                "mode",
                mode,
                options=list(
                    "simple",
                    "complex"),
                default="simple")
            private$..labels <- jmvcore::OptionVariable$new(
                "labels",
                labels,
                suggested=list(
                    "id",
                    "nominal"),
                permitted=list(
                    "id",
                    "factor"))
            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..k <- jmvcore::OptionInteger$new(
                "k",
                k,
                default=2,
                min=1)
            private$..plot <- jmvcore::OptionBool$new(
                "plot",
                plot,
                default=FALSE)
            private$..plot1 <- jmvcore::OptionBool$new(
                "plot1",
                plot1,
                default=FALSE)
            private$..stress <- jmvcore::OptionBool$new(
                "stress",
                stress,
                default=FALSE)
            private$..plot3 <- jmvcore::OptionBool$new(
                "plot3",
                plot3,
                default=FALSE)
            private$..xlab <- jmvcore::OptionVariable$new(
                "xlab",
                xlab,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..ylab <- jmvcore::OptionVariable$new(
                "ylab",
                ylab,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..zlab <- jmvcore::OptionVariable$new(
                "zlab",
                zlab,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..plot2 <- jmvcore::OptionBool$new(
                "plot2",
                plot2,
                default=FALSE)
            private$..clust <- jmvcore::OptionOutput$new(
                "clust")
            private$..metric <- jmvcore::OptionList$new(
                "metric",
                metric,
                options=list(
                    "euclidean",
                    "manhattan",
                    "maximum"),
                default="euclidean")

            self$.addOption(private$..mode)
            self$.addOption(private$..labels)
            self$.addOption(private$..vars)
            self$.addOption(private$..k)
            self$.addOption(private$..plot)
            self$.addOption(private$..plot1)
            self$.addOption(private$..stress)
            self$.addOption(private$..plot3)
            self$.addOption(private$..xlab)
            self$.addOption(private$..ylab)
            self$.addOption(private$..zlab)
            self$.addOption(private$..plot2)
            self$.addOption(private$..clust)
            self$.addOption(private$..metric)
        }),
    active = list(
        mode = function() private$..mode$value,
        labels = function() private$..labels$value,
        vars = function() private$..vars$value,
        k = function() private$..k$value,
        plot = function() private$..plot$value,
        plot1 = function() private$..plot1$value,
        stress = function() private$..stress$value,
        plot3 = function() private$..plot3$value,
        xlab = function() private$..xlab$value,
        ylab = function() private$..ylab$value,
        zlab = function() private$..zlab$value,
        plot2 = function() private$..plot2$value,
        clust = function() private$..clust$value,
        metric = function() private$..metric$value),
    private = list(
        ..mode = NA,
        ..labels = NA,
        ..vars = NA,
        ..k = NA,
        ..plot = NA,
        ..plot1 = NA,
        ..stress = NA,
        ..plot3 = NA,
        ..xlab = NA,
        ..ylab = NA,
        ..zlab = NA,
        ..plot2 = NA,
        ..clust = NA,
        ..metric = NA)
)

mdsResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "mdsResults",
    inherit = jmvcore::Group,
    active = list(
        instructions = function() private$.items[["instructions"]],
        stressNote = function() private$.items[["stressNote"]],
        plot = function() private$.items[["plot"]],
        plot1 = function() private$.items[["plot1"]],
        plot2 = function() private$.items[["plot2"]],
        plot3 = function() private$.items[["plot3"]],
        text = function() private$.items[["text"]],
        clust = function() private$.items[["clust"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Multidimensional Scaling Plot",
                refs="snowCluster")
            self$add(jmvcore::Html$new(
                options=options,
                name="instructions",
                title="Instructions",
                visible=TRUE))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="stressNote",
                title="Stress value",
                visible=FALSE))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="MDS Plot",
                requiresData=TRUE,
                visible="(plot)",
                renderFun=".plot",
                clearWith=list(
                    "vars",
                    "labels",
                    "metric")))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot1",
                title="K-means Plot",
                requiresData=TRUE,
                visible="(plot1)",
                renderFun=".plot1",
                clearWith=list(
                    "vars",
                    "labels",
                    "k")))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot2",
                title="3D Scatter Plot",
                requiresData=TRUE,
                visible="(plot2)",
                renderFun=".plot2",
                clearWith=list(
                    "xlab",
                    "ylab",
                    "zlab",
                    "metric")))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot3",
                title="Shepard Diagram",
                requiresData=TRUE,
                visible="(plot3)",
                renderFun=".plot3",
                clearWith=list(
                    "vars",
                    "labels",
                    "metric")))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title=""))
            self$add(jmvcore::Output$new(
                options=options,
                name="clust",
                title="Clustering",
                varTitle="Clustering",
                measureType="nominal",
                clearWith=list(
                    "vars",
                    "labels",
                    "k",
                    "metric")))}))

mdsBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "mdsBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "snowCluster",
                name = "mds",
                version = c(1,0,0),
                options = options,
                results = mdsResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'none')
        }))

#' Multidimensional Scaling Plot
#'
#' 
#' @param mode .
#' @param data The data as a data frame.
#' @param labels .
#' @param vars .
#' @param k .
#' @param plot .
#' @param plot1 .
#' @param stress .
#' @param plot3 .
#' @param xlab .
#' @param ylab .
#' @param zlab .
#' @param plot2 .
#' @param metric .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$instructions} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$stressNote} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plot1} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plot2} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plot3} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$clust} \tab \tab \tab \tab \tab an output \cr
#' }
#'
#' @export
mds <- function(
    mode = "simple",
    data,
    labels,
    vars,
    k = 2,
    plot = FALSE,
    plot1 = FALSE,
    stress = FALSE,
    plot3 = FALSE,
    xlab,
    ylab,
    zlab,
    plot2 = FALSE,
    metric = "euclidean") {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("mds requires jmvcore to be installed (restart may be required)")

    if ( ! missing(labels)) labels <- jmvcore::resolveQuo(jmvcore::enquo(labels))
    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if ( ! missing(xlab)) xlab <- jmvcore::resolveQuo(jmvcore::enquo(xlab))
    if ( ! missing(ylab)) ylab <- jmvcore::resolveQuo(jmvcore::enquo(ylab))
    if ( ! missing(zlab)) zlab <- jmvcore::resolveQuo(jmvcore::enquo(zlab))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(labels), labels, NULL),
            `if`( ! missing(vars), vars, NULL),
            `if`( ! missing(xlab), xlab, NULL),
            `if`( ! missing(ylab), ylab, NULL),
            `if`( ! missing(zlab), zlab, NULL))


    options <- mdsOptions$new(
        mode = mode,
        labels = labels,
        vars = vars,
        k = k,
        plot = plot,
        plot1 = plot1,
        stress = stress,
        plot3 = plot3,
        xlab = xlab,
        ylab = ylab,
        zlab = zlab,
        plot2 = plot2,
        metric = metric)

    analysis <- mdsClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

