
# This file is automatically generated, you probably don't want to edit this

mfaOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "mfaOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars = NULL,
            facs = NULL,
            labels = NULL,
            group = "2,5,3,10,9,2",
            type = "n,s,s,s,s,s",
            gn = "a,b,c,d,e,f",
            eigen = TRUE,
            type1 = "coordinates",
            type2 = "coordinates",
            type3 = "coordinates",
            vari = FALSE,
            ind = FALSE,
            quan = FALSE,
            plot = FALSE,
            plot1 = FALSE,
            plot2 = FALSE,
            plot3 = FALSE,
            plot4 = FALSE,
            plot5 = FALSE,
            plot6 = FALSE,
            plot7 = FALSE,
            plot8 = FALSE,
            angle = 0, ...) {

            super$initialize(
                package="snowCluster",
                name="mfa",
                requiresData=TRUE,
                ...)

            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars)
            private$..facs <- jmvcore::OptionVariable$new(
                "facs",
                facs,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..labels <- jmvcore::OptionVariable$new(
                "labels",
                labels,
                suggested=list(
                    "id"),
                permitted=list(
                    "id",
                    "factor"))
            private$..group <- jmvcore::OptionString$new(
                "group",
                group,
                default="2,5,3,10,9,2")
            private$..type <- jmvcore::OptionString$new(
                "type",
                type,
                default="n,s,s,s,s,s")
            private$..gn <- jmvcore::OptionString$new(
                "gn",
                gn,
                default="a,b,c,d,e,f")
            private$..eigen <- jmvcore::OptionBool$new(
                "eigen",
                eigen,
                default=TRUE)
            private$..type1 <- jmvcore::OptionList$new(
                "type1",
                type1,
                options=list(
                    "coordinates",
                    "cos2",
                    "contribution"),
                default="coordinates")
            private$..type2 <- jmvcore::OptionList$new(
                "type2",
                type2,
                options=list(
                    "coordinates",
                    "cos2",
                    "contribution"),
                default="coordinates")
            private$..type3 <- jmvcore::OptionList$new(
                "type3",
                type3,
                options=list(
                    "coordinates",
                    "cos2",
                    "contribution"),
                default="coordinates")
            private$..vari <- jmvcore::OptionBool$new(
                "vari",
                vari,
                default=FALSE)
            private$..ind <- jmvcore::OptionBool$new(
                "ind",
                ind,
                default=FALSE)
            private$..quan <- jmvcore::OptionBool$new(
                "quan",
                quan,
                default=FALSE)
            private$..plot <- jmvcore::OptionBool$new(
                "plot",
                plot,
                default=FALSE)
            private$..plot1 <- jmvcore::OptionBool$new(
                "plot1",
                plot1,
                default=FALSE)
            private$..plot2 <- jmvcore::OptionBool$new(
                "plot2",
                plot2,
                default=FALSE)
            private$..plot3 <- jmvcore::OptionBool$new(
                "plot3",
                plot3,
                default=FALSE)
            private$..plot4 <- jmvcore::OptionBool$new(
                "plot4",
                plot4,
                default=FALSE)
            private$..plot5 <- jmvcore::OptionBool$new(
                "plot5",
                plot5,
                default=FALSE)
            private$..plot6 <- jmvcore::OptionBool$new(
                "plot6",
                plot6,
                default=FALSE)
            private$..plot7 <- jmvcore::OptionBool$new(
                "plot7",
                plot7,
                default=FALSE)
            private$..plot8 <- jmvcore::OptionBool$new(
                "plot8",
                plot8,
                default=FALSE)
            private$..angle <- jmvcore::OptionNumber$new(
                "angle",
                angle,
                min=0,
                max=90,
                default=0)

            self$.addOption(private$..vars)
            self$.addOption(private$..facs)
            self$.addOption(private$..labels)
            self$.addOption(private$..group)
            self$.addOption(private$..type)
            self$.addOption(private$..gn)
            self$.addOption(private$..eigen)
            self$.addOption(private$..type1)
            self$.addOption(private$..type2)
            self$.addOption(private$..type3)
            self$.addOption(private$..vari)
            self$.addOption(private$..ind)
            self$.addOption(private$..quan)
            self$.addOption(private$..plot)
            self$.addOption(private$..plot1)
            self$.addOption(private$..plot2)
            self$.addOption(private$..plot3)
            self$.addOption(private$..plot4)
            self$.addOption(private$..plot5)
            self$.addOption(private$..plot6)
            self$.addOption(private$..plot7)
            self$.addOption(private$..plot8)
            self$.addOption(private$..angle)
        }),
    active = list(
        vars = function() private$..vars$value,
        facs = function() private$..facs$value,
        labels = function() private$..labels$value,
        group = function() private$..group$value,
        type = function() private$..type$value,
        gn = function() private$..gn$value,
        eigen = function() private$..eigen$value,
        type1 = function() private$..type1$value,
        type2 = function() private$..type2$value,
        type3 = function() private$..type3$value,
        vari = function() private$..vari$value,
        ind = function() private$..ind$value,
        quan = function() private$..quan$value,
        plot = function() private$..plot$value,
        plot1 = function() private$..plot1$value,
        plot2 = function() private$..plot2$value,
        plot3 = function() private$..plot3$value,
        plot4 = function() private$..plot4$value,
        plot5 = function() private$..plot5$value,
        plot6 = function() private$..plot6$value,
        plot7 = function() private$..plot7$value,
        plot8 = function() private$..plot8$value,
        angle = function() private$..angle$value),
    private = list(
        ..vars = NA,
        ..facs = NA,
        ..labels = NA,
        ..group = NA,
        ..type = NA,
        ..gn = NA,
        ..eigen = NA,
        ..type1 = NA,
        ..type2 = NA,
        ..type3 = NA,
        ..vari = NA,
        ..ind = NA,
        ..quan = NA,
        ..plot = NA,
        ..plot1 = NA,
        ..plot2 = NA,
        ..plot3 = NA,
        ..plot4 = NA,
        ..plot5 = NA,
        ..plot6 = NA,
        ..plot7 = NA,
        ..plot8 = NA,
        ..angle = NA)
)

mfaResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "mfaResults",
    inherit = jmvcore::Group,
    active = list(
        instructions = function() private$.items[["instructions"]],
        eigen = function() private$.items[["eigen"]],
        vari = function() private$.items[["vari"]],
        ind = function() private$.items[["ind"]],
        quan = function() private$.items[["quan"]],
        plot8 = function() private$.items[["plot8"]],
        plot = function() private$.items[["plot"]],
        plot6 = function() private$.items[["plot6"]],
        plot7 = function() private$.items[["plot7"]],
        plot1 = function() private$.items[["plot1"]],
        plot2 = function() private$.items[["plot2"]],
        plot3 = function() private$.items[["plot3"]],
        plot4 = function() private$.items[["plot4"]],
        plot5 = function() private$.items[["plot5"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Multiple Factor Analysis",
                refs="snowCluster")
            self$add(jmvcore::Html$new(
                options=options,
                name="instructions",
                title="Instructions",
                visible=TRUE))
            self$add(jmvcore::Table$new(
                options=options,
                name="eigen",
                title="Eigenvalues",
                visible="(eigen)",
                clearWith=list(
                    "vars",
                    "facs",
                    "labels",
                    "group",
                    "type",
                    "gn"),
                columns=list(
                    list(
                        `name`="comp", 
                        `title`="Component", 
                        `type`="text"),
                    list(
                        `name`="eigen", 
                        `title`="Eigenvalue", 
                        `type`="number"),
                    list(
                        `name`="varProp", 
                        `title`="% of Variance", 
                        `type`="number"),
                    list(
                        `name`="varCum", 
                        `title`="Cumulative %", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="vari",
                title="`Groups of variables - ${type1}`",
                visible="(vari)",
                clearWith=list(
                    "vars",
                    "facs",
                    "labels",
                    "group",
                    "type",
                    "gn",
                    "type1"),
                columns=list(
                    list(
                        `name`="name", 
                        `title`="", 
                        `type`="text", 
                        `content`="($key)"),
                    list(
                        `name`="pc1", 
                        `title`="1", 
                        `type`="number", 
                        `superTitle`="Dimension"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="ind",
                title="`Individuals - ${type2}`",
                visible="(ind)",
                clearWith=list(
                    "vars",
                    "facs",
                    "labels",
                    "group",
                    "type",
                    "gn",
                    "type2"),
                columns=list(
                    list(
                        `name`="name", 
                        `title`="", 
                        `type`="text", 
                        `content`="($key)"),
                    list(
                        `name`="pc1", 
                        `title`="1", 
                        `type`="number", 
                        `superTitle`="Dimension"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="quan",
                title="`Quantitative variables - ${type3}`",
                visible="(quan)",
                clearWith=list(
                    "vars",
                    "facs",
                    "labels",
                    "group",
                    "type",
                    "gn",
                    "type3"),
                columns=list(
                    list(
                        `name`="name", 
                        `title`="", 
                        `type`="text", 
                        `content`="($key)"),
                    list(
                        `name`="pc1", 
                        `title`="1", 
                        `type`="number", 
                        `superTitle`="Dimension"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot8",
                title="Scree plot",
                requiresData=TRUE,
                refs="factoextra",
                visible="(plot8)",
                renderFun=".plot8",
                clearWith=list(
                    "vars",
                    "facs",
                    "labels",
                    "group",
                    "type",
                    "gn")))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="Variable groups",
                requiresData=TRUE,
                refs="factoextra",
                visible="(plot)",
                renderFun=".plot",
                clearWith=list(
                    "vars",
                    "facs",
                    "labels",
                    "group",
                    "type",
                    "gn",
                    "type1")))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot6",
                title="Contribution of groups to dimension 1",
                requiresData=TRUE,
                refs="factoextra",
                visible="(plot6)",
                renderFun=".plot6",
                clearWith=list(
                    "vars",
                    "facs",
                    "labels",
                    "group",
                    "type",
                    "gn",
                    "angle")))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot7",
                title="Contribution of groups to dimension 2",
                requiresData=TRUE,
                refs="factoextra",
                visible="(plot7)",
                renderFun=".plot7",
                clearWith=list(
                    "vars",
                    "facs",
                    "labels",
                    "group",
                    "type",
                    "gn",
                    "angle")))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot1",
                title="Quantitative variables by groups",
                requiresData=TRUE,
                refs="factoextra",
                visible="(plot1)",
                renderFun=".plot1",
                clearWith=list(
                    "vars",
                    "facs",
                    "labels",
                    "group",
                    "type",
                    "gn",
                    "type3")))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot2",
                title="Contribution to dimension 1",
                requiresData=TRUE,
                refs="factoextra",
                visible="(plot2)",
                renderFun=".plot2",
                clearWith=list(
                    "vars",
                    "facs",
                    "labels",
                    "group",
                    "type",
                    "gn",
                    "angle")))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot3",
                title="Contribution to dimension 2",
                requiresData=TRUE,
                refs="factoextra",
                visible="(plot3)",
                renderFun=".plot3",
                clearWith=list(
                    "vars",
                    "facs",
                    "labels",
                    "group",
                    "type",
                    "gn",
                    "angle")))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot4",
                title="Graph of individuals",
                requiresData=TRUE,
                refs="factoextra",
                visible="(plot4)",
                renderFun=".plot4",
                clearWith=list(
                    "vars",
                    "facs",
                    "labels",
                    "group",
                    "type",
                    "type2",
                    "gn")))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot5",
                title="Individuals by group",
                requiresData=TRUE,
                refs="factoextra",
                visible="(plot5)",
                renderFun=".plot5",
                clearWith=list(
                    "vars",
                    "facs",
                    "labels",
                    "group",
                    "type",
                    "gn",
                    "type2")))}))

mfaBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "mfaBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "snowCluster",
                name = "mfa",
                version = c(1,0,0),
                options = options,
                results = mfaResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Multiple Factor Analysis
#'
#' 
#' @param data The data as a data frame.
#' @param vars .
#' @param facs .
#' @param labels .
#' @param group .
#' @param type .
#' @param gn .
#' @param eigen .
#' @param type1 .
#' @param type2 .
#' @param type3 .
#' @param vari .
#' @param ind .
#' @param quan .
#' @param plot .
#' @param plot1 .
#' @param plot2 .
#' @param plot3 .
#' @param plot4 .
#' @param plot5 .
#' @param plot6 .
#' @param plot7 .
#' @param plot8 .
#' @param angle .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$instructions} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$eigen} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$vari} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$ind} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$quan} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$plot8} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plot6} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plot7} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plot1} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plot2} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plot3} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plot4} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plot5} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$eigen$asDF}
#'
#' \code{as.data.frame(results$eigen)}
#'
#' @export
mfa <- function(
    data,
    vars,
    facs,
    labels,
    group = "2,5,3,10,9,2",
    type = "n,s,s,s,s,s",
    gn = "a,b,c,d,e,f",
    eigen = TRUE,
    type1 = "coordinates",
    type2 = "coordinates",
    type3 = "coordinates",
    vari = FALSE,
    ind = FALSE,
    quan = FALSE,
    plot = FALSE,
    plot1 = FALSE,
    plot2 = FALSE,
    plot3 = FALSE,
    plot4 = FALSE,
    plot5 = FALSE,
    plot6 = FALSE,
    plot7 = FALSE,
    plot8 = FALSE,
    angle = 0) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("mfa requires jmvcore to be installed (restart may be required)")

    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if ( ! missing(facs)) facs <- jmvcore::resolveQuo(jmvcore::enquo(facs))
    if ( ! missing(labels)) labels <- jmvcore::resolveQuo(jmvcore::enquo(labels))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(vars), vars, NULL),
            `if`( ! missing(facs), facs, NULL),
            `if`( ! missing(labels), labels, NULL))

    for (v in facs) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- mfaOptions$new(
        vars = vars,
        facs = facs,
        labels = labels,
        group = group,
        type = type,
        gn = gn,
        eigen = eigen,
        type1 = type1,
        type2 = type2,
        type3 = type3,
        vari = vari,
        ind = ind,
        quan = quan,
        plot = plot,
        plot1 = plot1,
        plot2 = plot2,
        plot3 = plot3,
        plot4 = plot4,
        plot5 = plot5,
        plot6 = plot6,
        plot7 = plot7,
        plot8 = plot8,
        angle = angle)

    analysis <- mfaClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

