
# This file is automatically generated, you probably don't want to edit this

mfaOptions <- if (requireNamespace('jmvcore')) R6::R6Class(
    "mfaOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            labels = NULL,
            vars = NULL,
            k = 2,
            group = "1,3,4,3",
            type = "n,s,s,s",
            gn = "wine_type,Expert1, Expert2,Expert3",
            eigen = TRUE, ...) {

            super$initialize(
                package='snowCluster',
                name='mfa',
                requiresData=TRUE,
                ...)

            private$..labels <- jmvcore::OptionVariable$new(
                "labels",
                labels,
                suggested=list(
                    "id"),
                permitted=list(
                    "id",
                    "factor"))
            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric",
                    "factor"))
            private$..k <- jmvcore::OptionInteger$new(
                "k",
                k,
                min=1,
                max=100,
                default=2)
            private$..group <- jmvcore::OptionString$new(
                "group",
                group,
                default="1,3,4,3")
            private$..type <- jmvcore::OptionString$new(
                "type",
                type,
                default="n,s,s,s")
            private$..gn <- jmvcore::OptionString$new(
                "gn",
                gn,
                default="wine_type,Expert1, Expert2,Expert3")
            private$..eigen <- jmvcore::OptionBool$new(
                "eigen",
                eigen,
                default=TRUE)

            self$.addOption(private$..labels)
            self$.addOption(private$..vars)
            self$.addOption(private$..k)
            self$.addOption(private$..group)
            self$.addOption(private$..type)
            self$.addOption(private$..gn)
            self$.addOption(private$..eigen)
        }),
    active = list(
        labels = function() private$..labels$value,
        vars = function() private$..vars$value,
        k = function() private$..k$value,
        group = function() private$..group$value,
        type = function() private$..type$value,
        gn = function() private$..gn$value,
        eigen = function() private$..eigen$value),
    private = list(
        ..labels = NA,
        ..vars = NA,
        ..k = NA,
        ..group = NA,
        ..type = NA,
        ..gn = NA,
        ..eigen = NA)
)

mfaResults <- if (requireNamespace('jmvcore')) R6::R6Class(
    inherit = jmvcore::Group,
    active = list(
        eigen = function() private$.items[["eigen"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Multiple Factor Analysis",
                refs="snowCluster")
            self$add(jmvcore::Table$new(
                options=options,
                name="eigen",
                title="Eigenvalues",
                visible="(eigen)",
                clearWith=list(
                    "vars"),
                columns=list(
                    list(
                        `name`="comp", 
                        `title`="Component", 
                        `type`="text"),
                    list(
                        `name`="eigen", 
                        `title`="Eigenvalue", 
                        `type`="number"),
                    list(
                        `name`="varProp", 
                        `title`="% of Variance", 
                        `type`="number"),
                    list(
                        `name`="varCum", 
                        `title`="Cumulative %", 
                        `type`="number"))))}))

mfaBase <- if (requireNamespace('jmvcore')) R6::R6Class(
    "mfaBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = 'snowCluster',
                name = 'mfa',
                version = c(1,0,0),
                options = options,
                results = mfaResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Multiple Factor Analysis
#'
#' 
#' @param data The data as a data frame.
#' @param labels .
#' @param vars .
#' @param k .
#' @param group .
#' @param type .
#' @param gn .
#' @param eigen .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$eigen} \tab \tab \tab \tab \tab a table \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$eigen$asDF}
#'
#' \code{as.data.frame(results$eigen)}
#'
#' @export
mfa <- function(
    data,
    labels,
    vars,
    k = 2,
    group = "1,3,4,3",
    type = "n,s,s,s",
    gn = "wine_type,Expert1, Expert2,Expert3",
    eigen = TRUE) {

    if ( ! requireNamespace('jmvcore'))
        stop('mfa requires jmvcore to be installed (restart may be required)')

    if ( ! missing(labels)) labels <- jmvcore::resolveQuo(jmvcore::enquo(labels))
    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(labels), labels, NULL),
            `if`( ! missing(vars), vars, NULL))


    options <- mfaOptions$new(
        labels = labels,
        vars = vars,
        k = k,
        group = group,
        type = type,
        gn = gn,
        eigen = eigen)

    analysis <- mfaClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}
