
# This file is automatically generated, you probably don't want to edit this

mfaOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "mfaOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars = NULL,
            facs = NULL,
            labels = NULL,
            group = "2,5,3,10,9,2",
            type = "n,s,s,s,s,s",
            gn = "a,b,c,d,e,f",
            eigen = TRUE,
            colvar = "coordinates",
            rowvar = "coordinates",
            cg = FALSE,
            ci = FALSE,
            quanti = FALSE,
            quanvar = "coordinates",
            plot = FALSE,
            plot1 = FALSE,
            plot2 = FALSE,
            plot3 = FALSE,
            plot4 = FALSE,
            plot5 = FALSE,
            plot6 = FALSE,
            plot7 = FALSE,
            plot8 = FALSE, ...) {

            super$initialize(
                package="snowCluster",
                name="mfa",
                requiresData=TRUE,
                ...)

            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars)
            private$..facs <- jmvcore::OptionVariable$new(
                "facs",
                facs,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..labels <- jmvcore::OptionVariable$new(
                "labels",
                labels,
                suggested=list(
                    "id"),
                permitted=list(
                    "id",
                    "factor"))
            private$..group <- jmvcore::OptionString$new(
                "group",
                group,
                default="2,5,3,10,9,2")
            private$..type <- jmvcore::OptionString$new(
                "type",
                type,
                default="n,s,s,s,s,s")
            private$..gn <- jmvcore::OptionString$new(
                "gn",
                gn,
                default="a,b,c,d,e,f")
            private$..eigen <- jmvcore::OptionBool$new(
                "eigen",
                eigen,
                default=TRUE)
            private$..colvar <- jmvcore::OptionList$new(
                "colvar",
                colvar,
                options=list(
                    "coordinates",
                    "cos2",
                    "contribution"),
                default="coordinates")
            private$..rowvar <- jmvcore::OptionList$new(
                "rowvar",
                rowvar,
                options=list(
                    "coordinates",
                    "cos2",
                    "contribution"),
                default="coordinates")
            private$..cg <- jmvcore::OptionBool$new(
                "cg",
                cg,
                default=FALSE)
            private$..ci <- jmvcore::OptionBool$new(
                "ci",
                ci,
                default=FALSE)
            private$..quanti <- jmvcore::OptionBool$new(
                "quanti",
                quanti,
                default=FALSE)
            private$..quanvar <- jmvcore::OptionList$new(
                "quanvar",
                quanvar,
                options=list(
                    "coordinates",
                    "cos2",
                    "contribution"),
                default="coordinates")
            private$..plot <- jmvcore::OptionBool$new(
                "plot",
                plot,
                default=FALSE)
            private$..plot1 <- jmvcore::OptionBool$new(
                "plot1",
                plot1,
                default=FALSE)
            private$..plot2 <- jmvcore::OptionBool$new(
                "plot2",
                plot2,
                default=FALSE)
            private$..plot3 <- jmvcore::OptionBool$new(
                "plot3",
                plot3,
                default=FALSE)
            private$..plot4 <- jmvcore::OptionBool$new(
                "plot4",
                plot4,
                default=FALSE)
            private$..plot5 <- jmvcore::OptionBool$new(
                "plot5",
                plot5,
                default=FALSE)
            private$..plot6 <- jmvcore::OptionBool$new(
                "plot6",
                plot6,
                default=FALSE)
            private$..plot7 <- jmvcore::OptionBool$new(
                "plot7",
                plot7,
                default=FALSE)
            private$..plot8 <- jmvcore::OptionBool$new(
                "plot8",
                plot8,
                default=FALSE)

            self$.addOption(private$..vars)
            self$.addOption(private$..facs)
            self$.addOption(private$..labels)
            self$.addOption(private$..group)
            self$.addOption(private$..type)
            self$.addOption(private$..gn)
            self$.addOption(private$..eigen)
            self$.addOption(private$..colvar)
            self$.addOption(private$..rowvar)
            self$.addOption(private$..cg)
            self$.addOption(private$..ci)
            self$.addOption(private$..quanti)
            self$.addOption(private$..quanvar)
            self$.addOption(private$..plot)
            self$.addOption(private$..plot1)
            self$.addOption(private$..plot2)
            self$.addOption(private$..plot3)
            self$.addOption(private$..plot4)
            self$.addOption(private$..plot5)
            self$.addOption(private$..plot6)
            self$.addOption(private$..plot7)
            self$.addOption(private$..plot8)
        }),
    active = list(
        vars = function() private$..vars$value,
        facs = function() private$..facs$value,
        labels = function() private$..labels$value,
        group = function() private$..group$value,
        type = function() private$..type$value,
        gn = function() private$..gn$value,
        eigen = function() private$..eigen$value,
        colvar = function() private$..colvar$value,
        rowvar = function() private$..rowvar$value,
        cg = function() private$..cg$value,
        ci = function() private$..ci$value,
        quanti = function() private$..quanti$value,
        quanvar = function() private$..quanvar$value,
        plot = function() private$..plot$value,
        plot1 = function() private$..plot1$value,
        plot2 = function() private$..plot2$value,
        plot3 = function() private$..plot3$value,
        plot4 = function() private$..plot4$value,
        plot5 = function() private$..plot5$value,
        plot6 = function() private$..plot6$value,
        plot7 = function() private$..plot7$value,
        plot8 = function() private$..plot8$value),
    private = list(
        ..vars = NA,
        ..facs = NA,
        ..labels = NA,
        ..group = NA,
        ..type = NA,
        ..gn = NA,
        ..eigen = NA,
        ..colvar = NA,
        ..rowvar = NA,
        ..cg = NA,
        ..ci = NA,
        ..quanti = NA,
        ..quanvar = NA,
        ..plot = NA,
        ..plot1 = NA,
        ..plot2 = NA,
        ..plot3 = NA,
        ..plot4 = NA,
        ..plot5 = NA,
        ..plot6 = NA,
        ..plot7 = NA,
        ..plot8 = NA)
)

mfaResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "mfaResults",
    inherit = jmvcore::Group,
    active = list(
        instructions = function() private$.items[["instructions"]],
        eigen = function() private$.items[["eigen"]],
        cg = function() private$.items[["cg"]],
        ci = function() private$.items[["ci"]],
        quanti = function() private$.items[["quanti"]],
        plot8 = function() private$.items[["plot8"]],
        plot = function() private$.items[["plot"]],
        plot6 = function() private$.items[["plot6"]],
        plot7 = function() private$.items[["plot7"]],
        plot1 = function() private$.items[["plot1"]],
        plot2 = function() private$.items[["plot2"]],
        plot3 = function() private$.items[["plot3"]],
        plot4 = function() private$.items[["plot4"]],
        plot5 = function() private$.items[["plot5"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Multiple Factor Analysis",
                refs="snowCluster")
            self$add(jmvcore::Html$new(
                options=options,
                name="instructions",
                title="Instructions",
                visible=TRUE))
            self$add(jmvcore::Table$new(
                options=options,
                name="eigen",
                title="Eigenvalues",
                visible="(eigen)",
                clearWith=list(
                    "vars",
                    "groups",
                    "type",
                    "gn",
                    "colvar",
                    "rowvar",
                    "quanvar"),
                columns=list(
                    list(
                        `name`="comp", 
                        `title`="Component", 
                        `type`="text"),
                    list(
                        `name`="eigen", 
                        `title`="Eigenvalue", 
                        `type`="number"),
                    list(
                        `name`="varProp", 
                        `title`="% of Variance", 
                        `type`="number"),
                    list(
                        `name`="varCum", 
                        `title`="Cumulative %", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="cg",
                title="`Groups of variables - ${colvar}`",
                visible="(cg)",
                clearWith=list(
                    "vars",
                    "groups",
                    "type",
                    "gn",
                    "colvar",
                    "rowvar",
                    "quanvar"),
                columns=list(
                    list(
                        `name`="name", 
                        `title`="", 
                        `type`="text", 
                        `content`="($key)"),
                    list(
                        `name`="pc1", 
                        `title`="1", 
                        `type`="number", 
                        `superTitle`="Dimension"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="ci",
                title="`Individuals - ${rowvar}`",
                visible="(ci)",
                clearWith=list(
                    "vars",
                    "groups",
                    "type",
                    "gn",
                    "colvar",
                    "rowvar",
                    "quanvar"),
                columns=list(
                    list(
                        `name`="name", 
                        `title`="", 
                        `type`="text", 
                        `content`="($key)"),
                    list(
                        `name`="pc1", 
                        `title`="1", 
                        `type`="number", 
                        `superTitle`="Dimension"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="quanti",
                title="`Quantitative variables - ${quanvar}`",
                visible="(quanti)",
                clearWith=list(
                    "vars",
                    "groups",
                    "type",
                    "gn",
                    "colvar",
                    "rowvar",
                    "quanvar"),
                columns=list(
                    list(
                        `name`="name", 
                        `title`="", 
                        `type`="text", 
                        `content`="($key)"),
                    list(
                        `name`="pc1", 
                        `title`="1", 
                        `type`="number", 
                        `superTitle`="Dimension"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot8",
                title="Scree plot",
                requiresData=TRUE,
                refs="factoextra",
                visible="(plot8)",
                width=500,
                height=500,
                renderFun=".plot8",
                clearWith=list(
                    "vars",
                    "groups",
                    "type",
                    "gn",
                    "colvar",
                    "rowvar",
                    "quanvar")))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="Variable groups",
                requiresData=TRUE,
                refs="factoextra",
                visible="(plot)",
                width=500,
                height=500,
                renderFun=".plot",
                clearWith=list(
                    "vars",
                    "groups",
                    "type",
                    "gn",
                    "colvar",
                    "rowvar",
                    "quanvar")))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot6",
                title="Contribution of groups to dimension 1",
                requiresData=TRUE,
                refs="factoextra",
                visible="(plot6)",
                width=500,
                height=500,
                renderFun=".plot6",
                clearWith=list(
                    "vars",
                    "groups",
                    "type",
                    "gn",
                    "colvar",
                    "rowvar",
                    "quanvar")))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot7",
                title="Contribution of groups to dimension 2",
                requiresData=TRUE,
                refs="factoextra",
                visible="(plot7)",
                width=500,
                height=500,
                renderFun=".plot7",
                clearWith=list(
                    "vars",
                    "groups",
                    "type",
                    "gn",
                    "colvar",
                    "rowvar",
                    "quanvar")))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot1",
                title="Quantitative variables by groups",
                requiresData=TRUE,
                refs="factoextra",
                visible="(plot1)",
                width=700,
                height=700,
                renderFun=".plot1",
                clearWith=list(
                    "vars",
                    "groups",
                    "type",
                    "gn",
                    "colvar",
                    "rowvar",
                    "quanvar")))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot2",
                title="Contribution to dimension 1",
                requiresData=TRUE,
                refs="factoextra",
                visible="(plot2)",
                width=500,
                height=500,
                renderFun=".plot2",
                clearWith=list(
                    "vars",
                    "groups",
                    "type",
                    "gn",
                    "colvar",
                    "rowvar",
                    "quanvar")))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot3",
                title="Contribution to dimension 2",
                requiresData=TRUE,
                refs="factoextra",
                visible="(plot3)",
                width=500,
                height=500,
                renderFun=".plot3",
                clearWith=list(
                    "vars",
                    "groups",
                    "type",
                    "gn",
                    "colvar",
                    "rowvar",
                    "quanvar")))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot4",
                title="Graph of individuals",
                requiresData=TRUE,
                refs="factoextra",
                visible="(plot4)",
                width=500,
                height=500,
                renderFun=".plot4",
                clearWith=list(
                    "vars",
                    "groups",
                    "type",
                    "gn",
                    "colvar",
                    "rowvar",
                    "quanvar")))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot5",
                title="Individuals by group",
                requiresData=TRUE,
                refs="factoextra",
                visible="(plot5)",
                width=600,
                height=600,
                renderFun=".plot5",
                clearWith=list(
                    "vars",
                    "groups",
                    "type",
                    "gn",
                    "colvar",
                    "rowvar",
                    "quanvar")))}))

mfaBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "mfaBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "snowCluster",
                name = "mfa",
                version = c(1,0,0),
                options = options,
                results = mfaResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Multiple Factor Analysis
#'
#' 
#' @param data The data as a data frame.
#' @param vars .
#' @param facs .
#' @param labels .
#' @param group .
#' @param type .
#' @param gn .
#' @param eigen .
#' @param colvar .
#' @param rowvar .
#' @param cg .
#' @param ci .
#' @param quanti .
#' @param quanvar .
#' @param plot .
#' @param plot1 .
#' @param plot2 .
#' @param plot3 .
#' @param plot4 .
#' @param plot5 .
#' @param plot6 .
#' @param plot7 .
#' @param plot8 .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$instructions} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$eigen} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$cg} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$ci} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$quanti} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$plot8} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plot6} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plot7} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plot1} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plot2} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plot3} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plot4} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plot5} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$eigen$asDF}
#'
#' \code{as.data.frame(results$eigen)}
#'
#' @export
mfa <- function(
    data,
    vars,
    facs,
    labels,
    group = "2,5,3,10,9,2",
    type = "n,s,s,s,s,s",
    gn = "a,b,c,d,e,f",
    eigen = TRUE,
    colvar = "coordinates",
    rowvar = "coordinates",
    cg = FALSE,
    ci = FALSE,
    quanti = FALSE,
    quanvar = "coordinates",
    plot = FALSE,
    plot1 = FALSE,
    plot2 = FALSE,
    plot3 = FALSE,
    plot4 = FALSE,
    plot5 = FALSE,
    plot6 = FALSE,
    plot7 = FALSE,
    plot8 = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("mfa requires jmvcore to be installed (restart may be required)")

    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if ( ! missing(facs)) facs <- jmvcore::resolveQuo(jmvcore::enquo(facs))
    if ( ! missing(labels)) labels <- jmvcore::resolveQuo(jmvcore::enquo(labels))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(vars), vars, NULL),
            `if`( ! missing(facs), facs, NULL),
            `if`( ! missing(labels), labels, NULL))

    for (v in facs) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- mfaOptions$new(
        vars = vars,
        facs = facs,
        labels = labels,
        group = group,
        type = type,
        gn = gn,
        eigen = eigen,
        colvar = colvar,
        rowvar = rowvar,
        cg = cg,
        ci = ci,
        quanti = quanti,
        quanvar = quanvar,
        plot = plot,
        plot1 = plot1,
        plot2 = plot2,
        plot3 = plot3,
        plot4 = plot4,
        plot5 = plot5,
        plot6 = plot6,
        plot7 = plot7,
        plot8 = plot8)

    analysis <- mfaClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

