
# This file is automatically generated, you probably don't want to edit this

pcaOptions <- if (requireNamespace('jmvcore')) R6::R6Class(
    "pcaOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            labels = NULL,
            vars = NULL,
            plot = TRUE,
            plot1 = TRUE,
            plot2 = TRUE, ...) {

            super$initialize(
                package='snowCluster',
                name='pca',
                requiresData=TRUE,
                ...)

            private$..labels <- jmvcore::OptionVariable$new(
                "labels",
                labels,
                suggested=list(
                    "id"),
                permitted=list(
                    "id",
                    "factor"))
            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..plot <- jmvcore::OptionBool$new(
                "plot",
                plot,
                default=TRUE)
            private$..plot1 <- jmvcore::OptionBool$new(
                "plot1",
                plot1,
                default=TRUE)
            private$..plot2 <- jmvcore::OptionBool$new(
                "plot2",
                plot2,
                default=TRUE)

            self$.addOption(private$..labels)
            self$.addOption(private$..vars)
            self$.addOption(private$..plot)
            self$.addOption(private$..plot1)
            self$.addOption(private$..plot2)
        }),
    active = list(
        labels = function() private$..labels$value,
        vars = function() private$..vars$value,
        plot = function() private$..plot$value,
        plot1 = function() private$..plot1$value,
        plot2 = function() private$..plot2$value),
    private = list(
        ..labels = NA,
        ..vars = NA,
        ..plot = NA,
        ..plot1 = NA,
        ..plot2 = NA)
)

pcaResults <- if (requireNamespace('jmvcore')) R6::R6Class(
    inherit = jmvcore::Group,
    active = list(
        plot = function() private$.items[["plot"]],
        plot1 = function() private$.items[["plot1"]],
        plot2 = function() private$.items[["plot2"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="PCA Plot")
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="Variable Contributions",
                requiresData=TRUE,
                refs="factoextra",
                visible="(plot)",
                width=500,
                height=500,
                renderFun=".plot"))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot1",
                title="Individual Plot",
                requiresData=TRUE,
                refs="factoextra",
                visible="(plot1)",
                width=500,
                height=500,
                renderFun=".plot1"))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot2",
                title="Biplot",
                requiresData=TRUE,
                refs="factoextra",
                visible="(plot2)",
                width=500,
                height=500,
                renderFun=".plot2"))}))

pcaBase <- if (requireNamespace('jmvcore')) R6::R6Class(
    "pcaBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = 'snowCluster',
                name = 'pca',
                version = c(1,0,0),
                options = options,
                results = pcaResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' PCA Plot
#'
#' 
#' @param data The data as a data frame.
#' @param labels .
#' @param vars .
#' @param plot .
#' @param plot1 .
#' @param plot2 .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plot1} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plot2} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' @export
pca <- function(
    data,
    labels,
    vars,
    plot = TRUE,
    plot1 = TRUE,
    plot2 = TRUE) {

    if ( ! requireNamespace('jmvcore'))
        stop('pca requires jmvcore to be installed (restart may be required)')

    if ( ! missing(labels)) labels <- jmvcore::resolveQuo(jmvcore::enquo(labels))
    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(labels), labels, NULL),
            `if`( ! missing(vars), vars, NULL))


    options <- pcaOptions$new(
        labels = labels,
        vars = vars,
        plot = plot,
        plot1 = plot1,
        plot2 = plot2)

    analysis <- pcaClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}
