
# This file is automatically generated, you probably don't want to edit this

rocOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "rocOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            dep = NULL,
            covs = NULL,
            plot1 = FALSE,
            plot2 = FALSE,
            plot3 = FALSE,
            auc = FALSE,
            dif = FALSE,
            overall = FALSE,
            positive = NULL,
            optimalCutpoint = FALSE,
            specifiedCutpoint = FALSE,
            cutpointValue = 0,
            classificationTable = FALSE, ...) {

            super$initialize(
                package="snowCluster",
                name="roc",
                requiresData=TRUE,
                ...)

            private$..dep <- jmvcore::OptionVariable$new(
                "dep",
                dep,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..covs <- jmvcore::OptionVariables$new(
                "covs",
                covs)
            private$..plot1 <- jmvcore::OptionBool$new(
                "plot1",
                plot1,
                default=FALSE)
            private$..plot2 <- jmvcore::OptionBool$new(
                "plot2",
                plot2,
                default=FALSE)
            private$..plot3 <- jmvcore::OptionBool$new(
                "plot3",
                plot3,
                default=FALSE)
            private$..auc <- jmvcore::OptionBool$new(
                "auc",
                auc,
                default=FALSE)
            private$..dif <- jmvcore::OptionBool$new(
                "dif",
                dif,
                default=FALSE)
            private$..overall <- jmvcore::OptionBool$new(
                "overall",
                overall,
                default=FALSE)
            private$..positive <- jmvcore::OptionLevel$new(
                "positive",
                positive,
                variable="(dep)")
            private$..optimalCutpoint <- jmvcore::OptionBool$new(
                "optimalCutpoint",
                optimalCutpoint,
                default=FALSE)
            private$..specifiedCutpoint <- jmvcore::OptionBool$new(
                "specifiedCutpoint",
                specifiedCutpoint,
                default=FALSE)
            private$..cutpointValue <- jmvcore::OptionNumber$new(
                "cutpointValue",
                cutpointValue,
                default=0)
            private$..classificationTable <- jmvcore::OptionBool$new(
                "classificationTable",
                classificationTable,
                default=FALSE)

            self$.addOption(private$..dep)
            self$.addOption(private$..covs)
            self$.addOption(private$..plot1)
            self$.addOption(private$..plot2)
            self$.addOption(private$..plot3)
            self$.addOption(private$..auc)
            self$.addOption(private$..dif)
            self$.addOption(private$..overall)
            self$.addOption(private$..positive)
            self$.addOption(private$..optimalCutpoint)
            self$.addOption(private$..specifiedCutpoint)
            self$.addOption(private$..cutpointValue)
            self$.addOption(private$..classificationTable)
        }),
    active = list(
        dep = function() private$..dep$value,
        covs = function() private$..covs$value,
        plot1 = function() private$..plot1$value,
        plot2 = function() private$..plot2$value,
        plot3 = function() private$..plot3$value,
        auc = function() private$..auc$value,
        dif = function() private$..dif$value,
        overall = function() private$..overall$value,
        positive = function() private$..positive$value,
        optimalCutpoint = function() private$..optimalCutpoint$value,
        specifiedCutpoint = function() private$..specifiedCutpoint$value,
        cutpointValue = function() private$..cutpointValue$value,
        classificationTable = function() private$..classificationTable$value),
    private = list(
        ..dep = NA,
        ..covs = NA,
        ..plot1 = NA,
        ..plot2 = NA,
        ..plot3 = NA,
        ..auc = NA,
        ..dif = NA,
        ..overall = NA,
        ..positive = NA,
        ..optimalCutpoint = NA,
        ..specifiedCutpoint = NA,
        ..cutpointValue = NA,
        ..classificationTable = NA)
)

rocResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "rocResults",
    inherit = jmvcore::Group,
    active = list(
        instructions = function() private$.items[["instructions"]],
        text = function() private$.items[["text"]],
        plot1 = function() private$.items[["plot1"]],
        plot2 = function() private$.items[["plot2"]],
        plot3 = function() private$.items[["plot3"]],
        auc = function() private$.items[["auc"]],
        dif = function() private$.items[["dif"]],
        overall = function() private$.items[["overall"]],
        optimalCutpoint = function() private$.items[["optimalCutpoint"]],
        specifiedCutpoint = function() private$.items[["specifiedCutpoint"]],
        classificationTable = function() private$.items[["classificationTable"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="ROC Analysis",
                refs="snowCluster")
            self$add(jmvcore::Html$new(
                options=options,
                name="instructions",
                title="Instructions",
                visible=TRUE))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title=""))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot1",
                title="ROC Curve",
                width=600,
                height=450,
                requiresData=TRUE,
                visible="(plot1)",
                renderFun=".plot1",
                refs="multipleROC",
                clearWith=list(
                    "covs",
                    "dep",
                    "positive")))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot2",
                title="Multiple ROC curves",
                width=600,
                height=450,
                requiresData=TRUE,
                visible="(plot2)",
                renderFun=".plot2",
                refs="multipleROC",
                clearWith=list(
                    "covs",
                    "dep",
                    "positive")))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot3",
                title="Faceted ROC plots",
                width=600,
                height=450,
                requiresData=TRUE,
                visible="(plot3)",
                renderFun=".plot3",
                refs="multipleROC",
                clearWith=list(
                    "covs",
                    "dep",
                    "positive")))
            self$add(jmvcore::Table$new(
                options=options,
                name="auc",
                title="A nonparametric test for AUC",
                visible="(auc)",
                clearWith=list(
                    "dep",
                    "covs",
                    "positive"),
                columns=list(
                    list(
                        `name`="name", 
                        `title`="", 
                        `type`="text", 
                        `content`="($key)"),
                    list(
                        `name`="auc", 
                        `title`="AUC", 
                        `type`="number"),
                    list(
                        `name`="p", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto,pvalue"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="dif",
                title="Pairwise comparisons for AUC difference",
                visible="(auc)",
                clearWith=list(
                    "dep",
                    "covs",
                    "positive"),
                columns=list(
                    list(
                        `name`="name", 
                        `title`="", 
                        `type`="text", 
                        `content`="($key)"),
                    list(
                        `name`="auc", 
                        `title`="AUC Difference", 
                        `type`="number"),
                    list(
                        `name`="lower", 
                        `title`="Lower", 
                        `type`="number", 
                        `superTitle`="95% CI"),
                    list(
                        `name`="upper", 
                        `title`="Upper", 
                        `type`="number", 
                        `superTitle`="95% CI"),
                    list(
                        `name`="p", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto,pvalue"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="overall",
                title="Overall test",
                rows=1,
                visible="(overall)",
                clearWith=list(
                    "dep",
                    "covs",
                    "positive"),
                columns=list(
                    list(
                        `name`="name", 
                        `title`="", 
                        `type`="text", 
                        `content`="Value"),
                    list(
                        `name`="Z", 
                        `title`="Wald \u03C7\u00B2", 
                        `type`="number"),
                    list(
                        `name`="p", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto,pvalue"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="optimalCutpoint",
                title="Optimal Cutpoint Performance",
                visible="(optimalCutpoint)",
                clearWith=list(
                    "dep",
                    "covs",
                    "positive",
                    "optimalCutpoint"),
                columns=list(
                    list(
                        `name`="predictor", 
                        `title`="Predictor", 
                        `type`="text"),
                    list(
                        `name`="n", 
                        `title`="N", 
                        `type`="integer"),
                    list(
                        `name`="auc", 
                        `title`="AUC", 
                        `type`="number"),
                    list(
                        `name`="cutpoint", 
                        `title`="Cutpoint", 
                        `type`="number"),
                    list(
                        `name`="direction", 
                        `title`="Direction", 
                        `type`="text"),
                    list(
                        `name`="sensitivity", 
                        `title`="Sensitivity", 
                        `type`="number", 
                        `format`="pc"),
                    list(
                        `name`="specificity", 
                        `title`="Specificity", 
                        `type`="number", 
                        `format`="pc"),
                    list(
                        `name`="youden", 
                        `title`="Youden's J", 
                        `type`="number"),
                    list(
                        `name`="accuracy", 
                        `title`="Accuracy", 
                        `type`="number", 
                        `format`="pc"),
                    list(
                        `name`="ppv", 
                        `title`="PPV", 
                        `type`="number", 
                        `format`="pc"),
                    list(
                        `name`="npv", 
                        `title`="NPV", 
                        `type`="number", 
                        `format`="pc"),
                    list(
                        `name`="lrPositive", 
                        `title`="LR+", 
                        `type`="number"),
                    list(
                        `name`="lrNegative", 
                        `title`="LR\u2212", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="specifiedCutpoint",
                title="Specified Cutpoint Performance",
                visible="(specifiedCutpoint)",
                clearWith=list(
                    "dep",
                    "covs",
                    "positive",
                    "specifiedCutpoint",
                    "cutpointValue"),
                columns=list(
                    list(
                        `name`="predictor", 
                        `title`="Predictor", 
                        `type`="text"),
                    list(
                        `name`="n", 
                        `title`="N", 
                        `type`="integer"),
                    list(
                        `name`="cutpoint", 
                        `title`="Cutpoint", 
                        `type`="number"),
                    list(
                        `name`="direction", 
                        `title`="Direction", 
                        `type`="text"),
                    list(
                        `name`="sensitivity", 
                        `title`="Sensitivity", 
                        `type`="number", 
                        `format`="pc"),
                    list(
                        `name`="specificity", 
                        `title`="Specificity", 
                        `type`="number", 
                        `format`="pc"),
                    list(
                        `name`="accuracy", 
                        `title`="Accuracy", 
                        `type`="number", 
                        `format`="pc"),
                    list(
                        `name`="balancedAccuracy", 
                        `title`="Balanced Accuracy", 
                        `type`="number", 
                        `format`="pc"),
                    list(
                        `name`="ppv", 
                        `title`="PPV", 
                        `type`="number", 
                        `format`="pc"),
                    list(
                        `name`="npv", 
                        `title`="NPV", 
                        `type`="number", 
                        `format`="pc"),
                    list(
                        `name`="lrPositive", 
                        `title`="LR+", 
                        `type`="number"),
                    list(
                        `name`="lrNegative", 
                        `title`="LR\u2212", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="classificationTable",
                title="Classification Table",
                visible="(classificationTable)",
                clearWith=list(
                    "dep",
                    "covs",
                    "positive",
                    "optimalCutpoint",
                    "specifiedCutpoint",
                    "cutpointValue",
                    "classificationTable"),
                columns=list(
                    list(
                        `name`="predictor", 
                        `title`="Predictor", 
                        `type`="text"),
                    list(
                        `name`="cutpointSource", 
                        `title`="Cutpoint Source", 
                        `type`="text"),
                    list(
                        `name`="cutpoint", 
                        `title`="Cutpoint", 
                        `type`="number"),
                    list(
                        `name`="direction", 
                        `title`="Direction", 
                        `type`="text"),
                    list(
                        `name`="truePositive", 
                        `title`="TP", 
                        `type`="integer", 
                        `superTitle`="Classification"),
                    list(
                        `name`="falseNegative", 
                        `title`="FN", 
                        `type`="integer", 
                        `superTitle`="Classification"),
                    list(
                        `name`="falsePositive", 
                        `title`="FP", 
                        `type`="integer", 
                        `superTitle`="Classification"),
                    list(
                        `name`="trueNegative", 
                        `title`="TN", 
                        `type`="integer", 
                        `superTitle`="Classification"),
                    list(
                        `name`="total", 
                        `title`="N", 
                        `type`="integer"))))}))

rocBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "rocBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "snowCluster",
                name = "roc",
                version = c(1,0,0),
                options = options,
                results = rocResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' ROC Analysis
#'
#' 
#' @param data .
#' @param dep .
#' @param covs .
#' @param plot1 .
#' @param plot2 .
#' @param plot3 .
#' @param auc .
#' @param dif .
#' @param overall .
#' @param positive .
#' @param optimalCutpoint .
#' @param specifiedCutpoint .
#' @param cutpointValue .
#' @param classificationTable .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$instructions} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$plot1} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plot2} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plot3} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$auc} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$dif} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$overall} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$optimalCutpoint} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$specifiedCutpoint} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$classificationTable} \tab \tab \tab \tab \tab a table \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$auc$asDF}
#'
#' \code{as.data.frame(results$auc)}
#'
#' @export
roc <- function(
    data,
    dep,
    covs,
    plot1 = FALSE,
    plot2 = FALSE,
    plot3 = FALSE,
    auc = FALSE,
    dif = FALSE,
    overall = FALSE,
    positive,
    optimalCutpoint = FALSE,
    specifiedCutpoint = FALSE,
    cutpointValue = 0,
    classificationTable = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("roc requires jmvcore to be installed (restart may be required)")

    if ( ! missing(dep)) dep <- jmvcore::resolveQuo(jmvcore::enquo(dep))
    if ( ! missing(covs)) covs <- jmvcore::resolveQuo(jmvcore::enquo(covs))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(dep), dep, NULL),
            `if`( ! missing(covs), covs, NULL))

    for (v in dep) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- rocOptions$new(
        dep = dep,
        covs = covs,
        plot1 = plot1,
        plot2 = plot2,
        plot3 = plot3,
        auc = auc,
        dif = dif,
        overall = overall,
        positive = positive,
        optimalCutpoint = optimalCutpoint,
        specifiedCutpoint = specifiedCutpoint,
        cutpointValue = cutpointValue,
        classificationTable = classificationTable)

    analysis <- rocClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

