
# This file is automatically generated, you probably don't want to edit this

timeclustOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "timeclustOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            k = 2,
            feature = NULL,
            item = NULL,
            value = NULL,
            plot = FALSE,
            width = 500,
            height = 500, ...) {

            super$initialize(
                package="snowCluster",
                name="timeclust",
                requiresData=TRUE,
                ...)

            private$..k <- jmvcore::OptionInteger$new(
                "k",
                k,
                default=2,
                min=2)
            private$..feature <- jmvcore::OptionVariable$new(
                "feature",
                feature,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..item <- jmvcore::OptionVariable$new(
                "item",
                item,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..value <- jmvcore::OptionVariable$new(
                "value",
                value,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..plot <- jmvcore::OptionBool$new(
                "plot",
                plot,
                default=FALSE)
            private$..width <- jmvcore::OptionInteger$new(
                "width",
                width,
                default=500)
            private$..height <- jmvcore::OptionInteger$new(
                "height",
                height,
                default=500)
            private$..clust <- jmvcore::OptionOutput$new(
                "clust")

            self$.addOption(private$..k)
            self$.addOption(private$..feature)
            self$.addOption(private$..item)
            self$.addOption(private$..value)
            self$.addOption(private$..plot)
            self$.addOption(private$..width)
            self$.addOption(private$..height)
            self$.addOption(private$..clust)
        }),
    active = list(
        k = function() private$..k$value,
        feature = function() private$..feature$value,
        item = function() private$..item$value,
        value = function() private$..value$value,
        plot = function() private$..plot$value,
        width = function() private$..width$value,
        height = function() private$..height$value,
        clust = function() private$..clust$value),
    private = list(
        ..k = NA,
        ..feature = NA,
        ..item = NA,
        ..value = NA,
        ..plot = NA,
        ..width = NA,
        ..height = NA,
        ..clust = NA)
)

timeclustResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "timeclustResults",
    inherit = jmvcore::Group,
    active = list(
        instructions = function() private$.items[["instructions"]],
        text = function() private$.items[["text"]],
        clust = function() private$.items[["clust"]],
        plot = function() private$.items[["plot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Time Series Clustering",
                refs="snowCluster")
            self$add(jmvcore::Html$new(
                options=options,
                name="instructions",
                title="Instructions",
                visible=TRUE))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title=""))
            self$add(jmvcore::Output$new(
                options=options,
                name="clust",
                title="Cluster",
                varTitle="Cluster",
                measureType="nominal",
                clearWith=list(
                    "item",
                    "feature",
                    "value",
                    "k")))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="Time series clustering",
                requiresData=TRUE,
                visible="(plot)",
                refs="widyr",
                renderFun=".plot",
                clearWith=list(
                    "item",
                    "feature",
                    "value",
                    "k",
                    "width",
                    "height")))}))

timeclustBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "timeclustBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "snowCluster",
                name = "timeclust",
                version = c(1,0,0),
                options = options,
                results = timeclustResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'none')
        }))

#' Time Series Clustering
#'
#' 
#' @param data The data as a data frame.
#' @param k .
#' @param feature .
#' @param item .
#' @param value .
#' @param plot .
#' @param width .
#' @param height .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$instructions} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$clust} \tab \tab \tab \tab \tab an output \cr
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' @export
timeclust <- function(
    data,
    k = 2,
    feature,
    item,
    value,
    plot = FALSE,
    width = 500,
    height = 500) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("timeclust requires jmvcore to be installed (restart may be required)")

    if ( ! missing(feature)) feature <- jmvcore::resolveQuo(jmvcore::enquo(feature))
    if ( ! missing(item)) item <- jmvcore::resolveQuo(jmvcore::enquo(item))
    if ( ! missing(value)) value <- jmvcore::resolveQuo(jmvcore::enquo(value))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(feature), feature, NULL),
            `if`( ! missing(item), item, NULL),
            `if`( ! missing(value), value, NULL))

    for (v in feature) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in item) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- timeclustOptions$new(
        k = k,
        feature = feature,
        item = item,
        value = value,
        plot = plot,
        width = width,
        height = height)

    analysis <- timeclustClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

